from __future__ import annotations

from cell_engine.core.provenance import SourceReference
from cell_engine.quantitative.geometry import build_hepatocyte_geometry, molecules_from_concentration_mM
from cell_engine.stochastic.cell_model import CYTOSOL, CellReactionModel
from cell_engine.stochastic.reactions import Reaction, ReactionNetwork, mass_action, michaelis_menten

DATE_VERIFIED = "2026-06-20"

UREA_CYCLE_SOURCES: dict[str, SourceReference] = {
    "cps1_structure": SourceReference(
        id="cps1_structure",
        title="Structure of human carbamoyl phosphate synthetase: the on/off switch of ureagenesis (Sci. Rep. 2015)",
        url="https://www.nature.com/articles/srep16950",
        source_type="primary_paper",
        date_verified=DATE_VERIFIED,
        notes="CPS1 is the liver-specific, rate-limiting first step: NH3 + HCO3- + 2 ATP -> carbamoyl phosphate; NAG-activated.",
    ),
    "urea_cycle_textbook": SourceReference(
        id="urea_cycle_textbook",
        title="Lehninger Principles of Biochemistry — the urea cycle",
        url="https://www.macmillanlearning.com/college/us/product/Lehninger-Principles-of-Biochemistry/p/131957066X",
        source_type="textbook",
        date_verified=DATE_VERIFIED,
        notes="Five-enzyme cycle (CPS1, OTC, ASS1, ASL, ARG1); ornithine regenerated; ~3 ATP per urea; 2 N per urea.",
    ),
}

ORNITHINE_BACKBONE = ("ornithine", "citrulline", "argininosuccinate", "arginine")


def _cps1() -> Reaction:
    # NH3 + 2 ATP -> carbamoyl phosphate + 2 ADP. Rate-limiting, MM in ammonia.
    # (HCO3- and Pi omitted in v1; NAG activation abstracted into Vmax.)
    return michaelis_menten(
        "cps1",
        reactants={"ammonia": 1, "ATP": 2},
        products={"carbamoyl_phosphate": 1, "ADP": 2},
        vmax_M_per_s=60.0 * 1.0e-6,   # kcat placeholder * [E]
        km_M=1.0e-3,                  # CPS1 ammonia Km ~1 mM (rate-limiting)
        substrate="ammonia",
        cosubstrate="ATP",
        cosubstrate_km_M=0.3e-3,
        source_id="cps1_structure",
        notes="Committed, rate-limiting, liver-specific step; Km grounded, kcat placeholder.",
    )


def build_urea_cycle_network(volume_l: float) -> ReactionNetwork:
    """The five-enzyme hepatic urea cycle on molecule counts.

    Net: ammonia + aspartate + 3 ATP -> urea + fumarate (+ ADP/AMP). Ornithine is
    consumed by OTC and regenerated by ARG1, so the ornithine backbone is a
    conserved carrier — the defining topology of the cycle. CPS1 is grounded;
    the rest are fast mass-action placeholders (correctness is the conservation
    laws, not these rate constants).
    """
    species = (
        "ammonia", "carbamoyl_phosphate", "ornithine", "citrulline", "aspartate",
        "argininosuccinate", "arginine", "fumarate", "urea", "ATP", "ADP", "AMP",
    )
    reactions: tuple[Reaction, ...] = (
        _cps1(),
        mass_action("otc", {"carbamoyl_phosphate": 1, "ornithine": 1}, {"citrulline": 1}, 1.0e6,
                    source_id="urea_cycle_textbook", notes="LUMPED: ornithine transcarbamylase."),
        mass_action("ass1", {"citrulline": 1, "aspartate": 1, "ATP": 1},
                    {"argininosuccinate": 1, "AMP": 1}, 1.0e6,
                    source_id="urea_cycle_textbook", notes="LUMPED: ATP->AMP (2 high-energy bonds)."),
        mass_action("asl", {"argininosuccinate": 1}, {"arginine": 1, "fumarate": 1}, 30.0,
                    source_id="urea_cycle_textbook", notes="LUMPED: argininosuccinate lyase."),
        mass_action("arg1", {"arginine": 1}, {"urea": 1, "ornithine": 1}, 30.0,
                    source_id="urea_cycle_textbook", notes="LUMPED: arginase regenerates ornithine (cycle closure)."),
    )
    return ReactionNetwork(species=species, reactions=reactions, volume_l=volume_l)


def ornithine_backbone_total(counts: dict[str, float]) -> float:
    """Conserved ornithine-carrier pool: the cycle moves it around but never net-makes it."""
    return sum(counts.get(s, 0.0) for s in ORNITHINE_BACKBONE)


def seed_urea_cycle_model(definition) -> CellReactionModel:
    """Seed the urea cycle with physiological-ish substrate/intermediate counts."""
    geometry = build_hepatocyte_geometry(definition)
    volume = geometry.volume_of(CYTOSOL)
    network = build_urea_cycle_network(volume)

    def n(mM: float) -> float:
        return molecules_from_concentration_mM(mM, volume)

    counts = {s: 0.0 for s in network.species}
    counts["ammonia"] = n(0.05)       # hepatic ammonia is kept low (~10-50 uM)
    counts["ornithine"] = n(0.3)      # cycle carrier
    counts["aspartate"] = n(1.0)      # second nitrogen donor
    counts["ATP"] = n(3.5)
    counts["ADP"] = n(1.2)
    counts["AMP"] = n(0.3)
    return CellReactionModel(network=network, counts=counts, t_s=0.0)
