"""Evidence-backed hepatocyte communication atlas and contact geometry.

This module separates three questions that are often collapsed into one:

1. Are two engine-owned surfaces geometrically in contact?
2. Do both bodies explicitly present a complementary molecular pair in the
   contacting membrane domains?
3. Are local patch presence, orientation, surface density, two-dimensional
   binding kinetics, pathway response and membrane-transport inputs complete?

The first gate is authoritative. The second can identify a qualitative candidate
for explicitly profiled bodies. The remaining gates fail closed and cannot alter
``CellState``.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import dist
from typing import Literal

from cell_engine.core.provenance import SourceReference
from cell_engine.core.serialization import to_plain
from cell_engine.quantitative.hepatocyte_counts import CELL_DIAMETER_UM
from cell_engine.quantitative.human_liver_open_atlas import (
    HUMAN_LIVER_OPEN_ATLAS_SOURCES,
    surface_protein_observation,
)
from cell_engine.quantitative.phh_glucose_validation import (
    PHH_GLUCOSE_VALIDATION_SOURCES,
    load_healthy_phh_glucose_validation,
)
from cell_engine.multicell.spatial_world import (
    SpatialBody,
    SpatialPairRelation,
    SpatialWorldState,
    build_single_hepatocyte_world,
)


DATE_VERIFIED = "2026-07-14"

CommunicationMode = Literal[
    "endocrine",
    "paracrine",
    "juxtacrine",
    "gap_junction",
    "host_entry",
]
SignalLocation = Literal[
    "extracellular",
    "plasma_membrane",
    "cytosol",
    "nucleus",
    "cell_cell_interface",
]


COMMUNICATION_SOURCES: dict[str, SourceReference] = {
    "reactome_insulin_receptor": SourceReference(
        id="reactome_insulin_receptor",
        title="Reactome: Signaling by Insulin receptor",
        url="https://reactome.org/content/detail/R-HSA-74752",
        source_type="database",
        date_verified=DATE_VERIFIED,
        notes="Curated human pathway: INSR autophosphorylation, IRS/SHC recruitment and PI3K/RAS signaling.",
    ),
    "glucagon_creb_hepatic_control": SourceReference(
        id="glucagon_creb_hepatic_control",
        title="CREB regulates hepatic gluconeogenesis through the coactivator PGC-1",
        url="https://www.nature.com/articles/35093131",
        source_type="primary_paper",
        date_verified=DATE_VERIFIED,
        notes="Supports the hepatic glucagon/cAMP/PKA/CREB-to-gluconeogenic-program direction; no project kinetic constants are inferred.",
    ),
    "reactome_hgf_met": SourceReference(
        id="reactome_hgf_met",
        title="Reactome: Signaling by MET",
        url="https://reactome.org/content/detail/R-HSA-6806834",
        source_type="database",
        date_verified=DATE_VERIFIED,
        notes="Curated human HGF/MET activation and downstream PI3K/AKT, RAS and STAT3 branches.",
    ),
    "reactome_il6_signaling": SourceReference(
        id="reactome_il6_signaling",
        title="Reactome: Interleukin-6 signaling",
        url="https://reactome.org/content/detail/R-HSA-1059683",
        source_type="database",
        date_verified=DATE_VERIFIED,
        notes="Curated human IL6/IL6R/gp130/JAK/STAT1-STAT3 and RAS-MAPK pathway.",
    ),
    "wnt_beta_catenin_liver_regeneration": SourceReference(
        id="wnt_beta_catenin_liver_regeneration",
        title="Conditional deletion of beta-catenin reveals its role in liver growth and regeneration",
        url="https://pubmed.ncbi.nlm.nih.gov/17101329/",
        source_type="primary_paper",
        date_verified=DATE_VERIFIED,
        notes="Mouse in-vivo evidence for a hepatic Wnt/beta-catenin support role; retained as mechanism evidence, not human PHH kinetics.",
    ),
    "reactome_adherens_junctions": SourceReference(
        id="reactome_adherens_junctions",
        title="Reactome: Adherens junctions interactions",
        url="https://reactome.org/content/detail/R-HSA-418990",
        source_type="database",
        date_verified=DATE_VERIFIED,
        notes="Curated human calcium-dependent cadherin trans-dimerization and junctional linkage to the cytoskeleton.",
    ),
    "hepatocyte_connexin32_signal_propagation": SourceReference(
        id="hepatocyte_connexin32_signal_propagation",
        title="Defective propagation of signals generated by sympathetic nerve stimulation in connexin32-deficient liver",
        url="https://pmc.ncbi.nlm.nih.gov/articles/PMC38468/",
        source_type="primary_paper",
        date_verified=DATE_VERIFIED,
        notes="Mouse in-vivo evidence that hepatocyte Cx32 gap junctions support intercellular propagation of a glycogen-mobilizing signal.",
    ),
    "huang2010_two_dimensional_binding": SourceReference(
        id="huang2010_two_dimensional_binding",
        title="The kinetics of two-dimensional TCR and pMHC interactions determine T-cell responsiveness",
        url="https://doi.org/10.1038/nature08944",
        source_type="primary_paper",
        date_verified="2026-07-15",
        notes=(
            "Directly demonstrates that membrane-anchored molecular recognition is "
            "governed by two-dimensional contact kinetics. The T-cell parameters "
            "are not transferred to hepatocytes; the study supports the required "
            "inputs of contact area, receptor/ligand density and 2D on/off rates."
        ),
    ),
    "yan2012_hbv_ntcp": SourceReference(
        id="yan2012_hbv_ntcp",
        title="Sodium taurocholate cotransporting polypeptide is a functional receptor for human hepatitis B and D virus",
        url="https://doi.org/10.7554/eLife.00049",
        source_type="primary_paper",
        date_verified="2026-07-15",
        notes="Supports the HBV preS1-NTCP attachment mechanism; it does not supply a complete entry-rate law.",
    ),
    "iwamoto2019_hbv_egfr": SourceReference(
        id="iwamoto2019_hbv_egfr",
        title="Epidermal growth factor receptor is a host-entry cofactor triggering hepatitis B virus internalization",
        url="https://doi.org/10.1073/pnas.1811064116",
        source_type="primary_paper",
        date_verified="2026-07-15",
        notes=(
            "Shows that HBV can attach through NTCP while internalization remains "
            "attenuated without functional EGFR; attachment and entry are therefore "
            "separate gates."
        ),
    ),
    "cajulao2022_gcgr_endocytosis": SourceReference(
        id="cajulao2022_gcgr_endocytosis",
        title="Glucagon receptor-mediated regulation of gluconeogenic gene transcription is endocytosis-dependent in primary hepatocytes",
        url="https://doi.org/10.1091/mbc.E21-09-0430",
        source_type="primary_paper",
        date_verified="2026-07-15",
        notes=(
            "Supports agonist-dependent clathrin/dynamin GCGR internalization and "
            "endosomal signaling. Glucagon is modeled as extracellular exposure, "
            "not as a cell-scale projectile."
        ),
    ),
    "kemas2021_phh_glucose": PHH_GLUCOSE_VALIDATION_SOURCES["kemas2021_phh_glucose"],
    "mallanna2016_phh_surfaceome": HUMAN_LIVER_OPEN_ATLAS_SOURCES[
        "mallanna2016_phh_surfaceome"
    ],
}


@dataclass(frozen=True)
class SignalStep:
    upstream: str
    downstream: str
    relation: str
    upstream_location: SignalLocation
    downstream_location: SignalLocation
    source_ids: tuple[str, ...]


@dataclass(frozen=True)
class CommunicationPathway:
    id: str
    label: str
    mode: CommunicationMode
    sender_context: str
    receiver_cell_type: str
    ligand_or_contact_molecule: str
    receptor_or_channel: str
    steps: tuple[SignalStep, ...]
    biological_output: str
    evidence_scope: str
    contact_required: bool
    extracellular_exposure_required: bool
    quantitative_kinetics_available: bool
    automatic_state_coupling: bool
    source_ids: tuple[str, ...]


SurfaceMoleculeRole = Literal[
    "receptor",
    "ligand",
    "adhesion",
    "channel",
    "cofactor",
    "transporter",
]


@dataclass(frozen=True)
class SurfaceMoleculeSpec:
    """Body-level molecular capability without invented patch occupancy."""

    id: str
    display_name: str
    role: SurfaceMoleculeRole
    compatible_partner_ids: tuple[str, ...]
    membrane_domains: tuple[str, ...]
    required_cofactor_ids: tuple[str, ...]
    transport_program: str | None
    surface_abundance_per_um2: float | None
    kon_2d_um2_per_molecule_s: float | None
    koff_s: float | None
    patch_distribution_available: bool
    orientation_model_available: bool
    evidence_scope: str
    source_ids: tuple[str, ...]


@dataclass(frozen=True)
class BodySurfaceProfile:
    body_id: str
    profile_id: str
    evidence_scope: str
    molecules: tuple[SurfaceMoleculeSpec, ...]


@dataclass(frozen=True)
class MolecularPairMatch:
    molecule_a_id: str
    molecule_b_id: str
    pathway_ids: tuple[str, ...]
    transport_programs: tuple[str, ...]
    required_cofactor_ids: tuple[str, ...]
    domain_compatible: bool
    local_patch_presence_observed: bool | None
    orientation_compatible: bool | None
    source_ids: tuple[str, ...]


@dataclass(frozen=True)
class ContactEventChain:
    """Geometry-to-transport gate audit for one engine-owned body pair."""

    contact_id: str
    contact_event: str
    body_a: str
    body_b: str
    body_a_kind: str
    body_b_kind: str
    geometric_contact: bool
    geometry_gate_status: str
    membrane_domain_a: str | None
    membrane_domain_b: str | None
    contact_patch_area_available: bool
    molecular_matches: tuple[MolecularPairMatch, ...]
    candidate_pathway_ids: tuple[str, ...]
    receptor_ligand_density_available: bool
    two_dimensional_kinetics_available: bool
    molecular_recognition_status: str
    signaling_status: str
    transport_status: str
    transport_programs: tuple[str, ...]
    emitted_events: tuple[str, ...]
    may_drive_cell_state: bool
    blockers: tuple[str, ...]
    source_ids: tuple[str, ...]


@dataclass(frozen=True)
class CellGeometry:
    id: str
    cell_type: str
    center_um: tuple[float, float, float]
    radius_um: float
    shape_kind: str
    geometry_status: str


@dataclass(frozen=True)
class ContactGeometry:
    id: str
    cell_a: str
    cell_b: str
    center_distance_um: float
    summed_radii_um: float
    surface_gap_um: float
    overlap_depth_um: float
    geometric_contact: bool
    contact_event: str
    contact_input_active: bool
    contact_face_a_id: str | None
    contact_face_b_id: str | None
    membrane_domain_a: str | None
    membrane_domain_b: str | None
    contact_patch_polygon_um: tuple[tuple[float, float, float], ...]
    contact_patch_area_um2: float | None
    contact_patch_status: str
    candidate_pathway_ids: tuple[str, ...]
    closest_point_a_um: tuple[float, float, float] | None = None
    closest_point_b_um: tuple[float, float, float] | None = None
    normal_a_to_b: tuple[float, float, float] | None = None
    relative_normal_velocity_um_s: float | None = None
    normal_load_nN: float | None = None
    force_status: str = "unknown"


@dataclass(frozen=True)
class SignalExposure:
    id: str
    pathway_id: str
    sender_id: str
    receiver_id: str
    ligand_value: float | None = None
    ligand_unit: str | None = None
    receptor_surface_abundance: float | None = None
    receptor_abundance_unit: str | None = None
    local_receptor_or_junction_present: bool | None = None
    ligand_or_partner_match_at_patch: bool | None = None
    orientation_compatible_at_patch: bool | None = None
    matched_downstream_response_available: bool = False
    matched_response_ids: tuple[str, ...] = ()
    contact_id: str | None = None
    source_ids: tuple[str, ...] = ()


@dataclass(frozen=True)
class SignalChainEvaluation:
    exposure_id: str
    pathway_id: str
    status: str
    mechanism_supported: bool
    geometry_gate_passed: bool | None
    local_surface_gate_passed: bool | None
    local_surface_gate_status: str
    ligand_measurement_available: bool
    receptor_measurement_available: bool
    matched_response_available: bool
    predicted_receptor_activation: float | None
    predicted_downstream_response: float | None
    may_drive_cell_state: bool
    matched_response_ids: tuple[str, ...]
    source_ids: tuple[str, ...]
    blockers: tuple[str, ...]


@dataclass(frozen=True)
class HepatocyteCommunicationSystem:
    version: str
    species: str
    cell_type: str
    status: str
    pathways: tuple[CommunicationPathway, ...]
    reference_cells: tuple[CellGeometry, ...]
    reference_contacts: tuple[ContactGeometry, ...]
    body_surface_profiles: tuple[BodySurfaceProfile, ...]
    contact_event_chains: tuple[ContactEventChain, ...]
    evaluated_exposures: tuple[SignalChainEvaluation, ...]
    measured_exposure_count: int
    matched_response_evidence_count: int
    quantitative_pathway_count: int
    active_signal_count: int
    recognition_candidate_count: int
    active_transport_count: int
    automatic_state_coupling: bool
    event_chain_contract: str
    reference_geometry_is_biological_observation: bool
    limitations: tuple[str, ...]

    def to_dict(self) -> dict[str, object]:
        return to_plain(self)


def _step(
    upstream: str,
    downstream: str,
    relation: str,
    upstream_location: SignalLocation,
    downstream_location: SignalLocation,
    source_id: str,
) -> SignalStep:
    return SignalStep(
        upstream=upstream,
        downstream=downstream,
        relation=relation,
        upstream_location=upstream_location,
        downstream_location=downstream_location,
        source_ids=(source_id,),
    )


def build_hepatocyte_communication_atlas() -> tuple[CommunicationPathway, ...]:
    """Return mechanism topology without inventing receptor occupancy or rates."""

    return (
        CommunicationPathway(
            id="insulin_insr_pi3k_akt",
            label="Insulin -> INSR -> IRS/PI3K/AKT",
            mode="endocrine",
            sender_context="pancreatic_beta_cell_via_circulation",
            receiver_cell_type="adult_human_hepatocyte",
            ligand_or_contact_molecule="insulin",
            receptor_or_channel="INSR",
            steps=(
                _step("insulin", "INSR", "binds_and_activates", "extracellular", "plasma_membrane", "reactome_insulin_receptor"),
                _step("activated_INSR", "IRS_SHC", "phosphorylates_and_recruits", "plasma_membrane", "cytosol", "reactome_insulin_receptor"),
                _step("IRS_SHC", "PI3K_AKT_and_RAS_MAPK", "activates", "cytosol", "cytosol", "reactome_insulin_receptor"),
            ),
            biological_output="fed-state metabolic and transcriptional regulation",
            evidence_scope="curated_human_pathway; current project exposure is peripheral plasma rather than matched portal concentration",
            contact_required=False,
            extracellular_exposure_required=True,
            quantitative_kinetics_available=False,
            automatic_state_coupling=False,
            source_ids=("reactome_insulin_receptor",),
        ),
        CommunicationPathway(
            id="glucagon_gcgr_camp_pka_creb",
            label="Glucagon -> GCGR -> cAMP/PKA/CREB",
            mode="endocrine",
            sender_context="pancreatic_alpha_cell_via_circulation",
            receiver_cell_type="adult_human_hepatocyte",
            ligand_or_contact_molecule="glucagon",
            receptor_or_channel="GCGR",
            steps=(
                _step("glucagon", "GCGR_Gs", "binds_and_activates", "extracellular", "plasma_membrane", "glucagon_creb_hepatic_control"),
                _step("GCGR_Gs", "adenylyl_cyclase_cAMP_PKA", "activates", "plasma_membrane", "cytosol", "glucagon_creb_hepatic_control"),
                _step("activated_GCGR", "GCGR_early_endosome", "clathrin_and_dynamin_dependent_internalization", "plasma_membrane", "cytosol", "cajulao2022_gcgr_endocytosis"),
                _step("GCGR_early_endosome", "endosomal_cAMP", "supports", "cytosol", "cytosol", "cajulao2022_gcgr_endocytosis"),
                _step("PKA", "CREB_PGC1A_program", "activates", "cytosol", "nucleus", "glucagon_creb_hepatic_control"),
            ),
            biological_output="glycogen mobilization and gluconeogenic gene program",
            evidence_scope="hepatic mechanism and receptor internalization supported; current project lacks matched portal exposure, human-PHH surface abundance and kinetic trajectories",
            contact_required=False,
            extracellular_exposure_required=True,
            quantitative_kinetics_available=False,
            automatic_state_coupling=False,
            source_ids=("glucagon_creb_hepatic_control", "cajulao2022_gcgr_endocytosis"),
        ),
        CommunicationPathway(
            id="hgf_met_regeneration",
            label="HGF -> MET -> PI3K/AKT and RAS/MAPK",
            mode="paracrine",
            sender_context="liver_stromal_and_injury_context",
            receiver_cell_type="adult_human_hepatocyte",
            ligand_or_contact_molecule="HGF",
            receptor_or_channel="MET",
            steps=(
                _step("HGF", "MET_dimer", "binds_and_dimerizes", "extracellular", "plasma_membrane", "reactome_hgf_met"),
                _step("MET_dimer", "phosphorylated_MET", "trans_autophosphorylates", "plasma_membrane", "plasma_membrane", "reactome_hgf_met"),
                _step("phosphorylated_MET", "PI3K_AKT_RAS_STAT3", "recruits_and_activates", "plasma_membrane", "cytosol", "reactome_hgf_met"),
            ),
            biological_output="survival, motility and regenerative mitogenic support",
            evidence_scope="curated_human mechanism; no matched healthy-PHH dose-time response loaded",
            contact_required=False,
            extracellular_exposure_required=True,
            quantitative_kinetics_available=False,
            automatic_state_coupling=False,
            source_ids=("reactome_hgf_met",),
        ),
        CommunicationPathway(
            id="il6_il6r_gp130_jak_stat3",
            label="IL-6 -> IL6R/gp130 -> JAK/STAT3",
            mode="paracrine",
            sender_context="immune_and_stromal_injury_context",
            receiver_cell_type="adult_human_hepatocyte",
            ligand_or_contact_molecule="IL6",
            receptor_or_channel="IL6R_IL6ST_gp130",
            steps=(
                _step("IL6", "IL6R_gp130_complex", "assembles", "extracellular", "plasma_membrane", "reactome_il6_signaling"),
                _step("IL6R_gp130_complex", "JAK", "activates", "plasma_membrane", "cytosol", "reactome_il6_signaling"),
                _step("JAK", "STAT1_STAT3", "phosphorylates", "cytosol", "cytosol", "reactome_il6_signaling"),
                _step("phosphorylated_STAT3", "IL6_response_genes", "translocates_and_regulates", "cytosol", "nucleus", "reactome_il6_signaling"),
            ),
            biological_output="acute-phase, survival and regenerative priming program",
            evidence_scope="curated_human mechanism; ligand/receptor/STAT3 trajectories are not loaded for the simulated cell",
            contact_required=False,
            extracellular_exposure_required=True,
            quantitative_kinetics_available=False,
            automatic_state_coupling=False,
            source_ids=("reactome_il6_signaling",),
        ),
        CommunicationPathway(
            id="wnt_fzd_lrp_beta_catenin",
            label="Wnt -> FZD/LRP -> beta-catenin",
            mode="paracrine",
            sender_context="zonal_endothelial_and_niche_context",
            receiver_cell_type="hepatocyte",
            ligand_or_contact_molecule="Wnt",
            receptor_or_channel="FZD_LRP",
            steps=(
                _step("Wnt", "FZD_LRP", "binds_and_activates", "extracellular", "plasma_membrane", "wnt_beta_catenin_liver_regeneration"),
                _step("FZD_LRP", "stabilized_beta_catenin", "stabilizes", "plasma_membrane", "cytosol", "wnt_beta_catenin_liver_regeneration"),
                _step("stabilized_beta_catenin", "beta_catenin_target_program", "translocates_and_regulates", "cytosol", "nucleus", "wnt_beta_catenin_liver_regeneration"),
            ),
            biological_output="zonal identity and regenerative support",
            evidence_scope="liver mechanism with mouse causal evidence; no human PHH effect-size or exposure field is assigned",
            contact_required=False,
            extracellular_exposure_required=True,
            quantitative_kinetics_available=False,
            automatic_state_coupling=False,
            source_ids=("wnt_beta_catenin_liver_regeneration",),
        ),
        CommunicationPathway(
            id="hbv_pres1_ntcp_egfr_entry",
            label="HBV preS1 -> NTCP/EGFR -> internalization",
            mode="host_entry",
            sender_context="explicit_complete_hbv_virion",
            receiver_cell_type="susceptible_human_hepatocyte",
            ligand_or_contact_molecule="HBV_preS1",
            receptor_or_channel="SLC10A1_NTCP_with_EGFR",
            steps=(
                _step("HBV_preS1", "SLC10A1_NTCP", "attaches", "cell_cell_interface", "plasma_membrane", "yan2012_hbv_ntcp"),
                _step("HBV_preS1_NTCP", "NTCP_EGFR_complex", "requires_functional_host_cofactor", "plasma_membrane", "plasma_membrane", "iwamoto2019_hbv_egfr"),
                _step("HBV_NTCP_EGFR_complex", "endocytic_vesicle", "internalizes", "plasma_membrane", "cytosol", "iwamoto2019_hbv_egfr"),
            ),
            biological_output="viral attachment candidate followed by separately gated host-cell entry",
            evidence_scope="human-virus receptor and host-cofactor mechanism supported; local abundance, 2D binding kinetics, entry probability and PHH trajectory are not loaded",
            contact_required=True,
            extracellular_exposure_required=False,
            quantitative_kinetics_available=False,
            automatic_state_coupling=False,
            source_ids=("yan2012_hbv_ntcp", "iwamoto2019_hbv_egfr"),
        ),
        CommunicationPathway(
            id="cdh1_adherens_contact",
            label="E-cadherin trans-contact -> adherens junction",
            mode="juxtacrine",
            sender_context="adjacent_epithelial_cell",
            receiver_cell_type="hepatocyte",
            ligand_or_contact_molecule="CDH1_on_neighbor",
            receptor_or_channel="CDH1_on_receiver",
            steps=(
                _step("CDH1_cell_A", "CDH1_cell_B", "calcium_dependent_trans_dimerization", "cell_cell_interface", "cell_cell_interface", "reactome_adherens_junctions"),
                _step("CDH1_trans_dimer", "catenin_actin_junction", "links", "plasma_membrane", "cytosol", "reactome_adherens_junctions"),
            ),
            biological_output="adhesion, polarity and contact-dependent growth control",
            evidence_scope="curated_human junction mechanism; hepatocyte-specific bond density and force law are not loaded",
            contact_required=True,
            extracellular_exposure_required=False,
            quantitative_kinetics_available=False,
            automatic_state_coupling=False,
            source_ids=("reactome_adherens_junctions",),
        ),
        CommunicationPathway(
            id="gjb1_connexin32_gap_junction",
            label="Cx32 gap junction intercellular transfer",
            mode="gap_junction",
            sender_context="adjacent_hepatocyte",
            receiver_cell_type="hepatocyte",
            ligand_or_contact_molecule="neighbor_cytosolic_small_signal",
            receptor_or_channel="GJB1_Cx32_gap_junction",
            steps=(
                _step("GJB1_connexon_cell_A", "GJB1_connexon_cell_B", "docks_across_contact", "cell_cell_interface", "cell_cell_interface", "hepatocyte_connexin32_signal_propagation"),
                _step("small_ion_or_second_messenger", "neighbor_cytosol", "passes_through_open_gap_junction", "cytosol", "cytosol", "hepatocyte_connexin32_signal_propagation"),
            ),
            biological_output="coordination of metabolic and calcium-associated signals between hepatocytes",
            evidence_scope="mouse in-vivo hepatocyte signal-propagation evidence; human channel abundance, permeability and gating are not assigned",
            contact_required=True,
            extracellular_exposure_required=False,
            quantitative_kinetics_available=False,
            automatic_state_coupling=False,
            source_ids=("hepatocyte_connexin32_signal_propagation",),
        ),
    )


def _surface_molecule(
    molecule_id: str,
    display_name: str,
    role: SurfaceMoleculeRole,
    *,
    partners: tuple[str, ...] = (),
    domains: tuple[str, ...] = ("unknown",),
    cofactors: tuple[str, ...] = (),
    transport_program: str | None = None,
    surfaceome_gene: str | None = None,
    evidence_scope: str,
    source_ids: tuple[str, ...],
) -> SurfaceMoleculeSpec:
    observation = (
        surface_protein_observation(surfaceome_gene)
        if surfaceome_gene is not None
        else None
    )
    if observation is not None:
        evidence_scope = (
            f"{evidence_scope}; identity observed by primary-human-hepatocyte "
            "cell-surface capture, without density, membrane domain or orientation"
        )
        source_ids = tuple(
            dict.fromkeys((*source_ids, "mallanna2016_phh_surfaceome"))
        )
    elif surfaceome_gene is not None:
        evidence_scope = (
            f"{evidence_scope}; not detected in the 2016 PHH surface-capture assay, "
            "which is not evidence of biological absence"
        )
    return SurfaceMoleculeSpec(
        id=molecule_id,
        display_name=display_name,
        role=role,
        compatible_partner_ids=partners,
        membrane_domains=domains,
        required_cofactor_ids=cofactors,
        transport_program=transport_program,
        surface_abundance_per_um2=None,
        kon_2d_um2_per_molecule_s=None,
        koff_s=None,
        patch_distribution_available=False,
        orientation_model_available=False,
        evidence_scope=evidence_scope,
        source_ids=source_ids,
    )


def _surface_profile_templates() -> dict[str, tuple[str, tuple[SurfaceMoleculeSpec, ...]]]:
    """Return qualitative identities; every quantitative binding field is null."""

    hepatocyte = (
        _surface_molecule(
            "CDH1",
            "E-cadherin",
            "adhesion",
            partners=("CDH1",),
            domains=("lateral",),
            cofactors=("extracellular_Ca2+",),
            surfaceome_gene="CDH1",
            evidence_scope="human cadherin trans-contact topology; no healthy-PHH patch density or bond mechanics",
            source_ids=("reactome_adherens_junctions",),
        ),
        _surface_molecule(
            "GJB1_Cx32",
            "Connexin 32 connexon",
            "channel",
            partners=("GJB1_Cx32",),
            domains=("lateral",),
            transport_program="gap_junction_small_solute_exchange",
            surfaceome_gene="GJB1",
            evidence_scope="hepatocyte gap-junction mechanism; human permeability and gating unavailable",
            source_ids=("hepatocyte_connexin32_signal_propagation",),
        ),
        _surface_molecule(
            "SLC10A1_NTCP",
            "NTCP",
            "receptor",
            partners=("HBV_preS1",),
            domains=("basolateral",),
            cofactors=("EGFR",),
            transport_program="hbv_receptor_cofactor_endocytic_entry",
            surfaceome_gene="SLC10A1",
            evidence_scope="human HBV attachment receptor with separately required EGFR-mediated internalization",
            source_ids=("yan2012_hbv_ntcp", "iwamoto2019_hbv_egfr"),
        ),
        _surface_molecule(
            "EGFR",
            "Epidermal growth factor receptor",
            "cofactor",
            domains=("basolateral",),
            surfaceome_gene="EGFR",
            evidence_scope="host-entry cofactor identity only; local NTCP-EGFR complex abundance unavailable",
            source_ids=("iwamoto2019_hbv_egfr",),
        ),
        _surface_molecule(
            "GCGR",
            "Glucagon receptor",
            "receptor",
            partners=("glucagon",),
            domains=("basolateral",),
            transport_program="gcgr_clathrin_dynamin_endocytosis",
            surfaceome_gene="GCGR",
            evidence_scope="surface and endosomal signaling topology; soluble exposure is not a collision body",
            source_ids=("glucagon_creb_hepatic_control", "cajulao2022_gcgr_endocytosis"),
        ),
        _surface_molecule(
            "INSR",
            "Insulin receptor",
            "receptor",
            partners=("insulin",),
            surfaceome_gene="INSR",
            evidence_scope="human pathway receptor identity; local exposure and receptor occupancy unavailable",
            source_ids=("reactome_insulin_receptor",),
        ),
        _surface_molecule(
            "MET",
            "Hepatocyte growth factor receptor",
            "receptor",
            partners=("HGF",),
            surfaceome_gene="MET",
            evidence_scope="human pathway receptor identity; local HGF dose-time response unavailable",
            source_ids=("reactome_hgf_met",),
        ),
        _surface_molecule(
            "IL6ST_gp130",
            "Interleukin-6 receptor subunit beta / gp130",
            "cofactor",
            partners=("IL6_IL6R_complex",),
            surfaceome_gene="IL6ST",
            evidence_scope="human IL-6 signaling coreceptor identity; complete local receptor complex unavailable",
            source_ids=("reactome_il6_signaling",),
        ),
        _surface_molecule(
            "ABCB11_BSEP",
            "Bile salt export pump",
            "transporter",
            surfaceome_gene="ABCB11",
            evidence_scope="primary-hepatocyte surface identity only; active surface density and transport law unavailable",
            source_ids=(),
        ),
        _surface_molecule(
            "ABCC2_MRP2",
            "Multidrug resistance-associated protein 2",
            "transporter",
            surfaceome_gene="ABCC2",
            evidence_scope="primary-hepatocyte surface identity only; active surface density and transport law unavailable",
            source_ids=(),
        ),
        _surface_molecule(
            "ABCB1_MDR1",
            "Multidrug resistance protein 1",
            "transporter",
            surfaceome_gene="ABCB1",
            evidence_scope="primary-hepatocyte surface identity only; active surface density and transport law unavailable",
            source_ids=(),
        ),
    )
    hbv = (
        _surface_molecule(
            "HBV_preS1",
            "HBV large-envelope preS1 domain",
            "ligand",
            partners=("SLC10A1_NTCP",),
            transport_program="hbv_receptor_cofactor_endocytic_entry",
            evidence_scope="complete-HBV attachment ligand identity; virion-level site count and 2D kinetics unavailable",
            source_ids=("yan2012_hbv_ntcp", "iwamoto2019_hbv_egfr"),
        ),
    )
    return {
        "adult_human_hepatocyte_surface_v1": (
            "qualitative adult-human-hepatocyte surface capability; body-level presence is not patch occupancy",
            hepatocyte,
        ),
        "hbv_virion_surface_v1": (
            "qualitative complete-HBV attachment capability; no infection probability",
            hbv,
        ),
    }


def build_body_surface_profiles(world: SpatialWorldState) -> tuple[BodySurfaceProfile, ...]:
    templates = _surface_profile_templates()
    profiles: list[BodySurfaceProfile] = []
    for body in world.bodies:
        if body.molecular_profile_id is None:
            continue
        if body.molecular_profile_id not in templates:
            raise ValueError(f"unknown molecular surface profile: {body.molecular_profile_id}")
        evidence_scope, molecules = templates[body.molecular_profile_id]
        profiles.append(BodySurfaceProfile(
            body_id=body.id,
            profile_id=body.molecular_profile_id,
            evidence_scope=evidence_scope,
            molecules=molecules,
        ))
    return tuple(profiles)


_MOLECULAR_PAIR_PATHWAYS: dict[frozenset[str], tuple[str, ...]] = {
    frozenset(("CDH1",)): ("cdh1_adherens_contact",),
    frozenset(("GJB1_Cx32",)): ("gjb1_connexin32_gap_junction",),
    frozenset(("HBV_preS1", "SLC10A1_NTCP")): ("hbv_pres1_ntcp_egfr_entry",),
}


def _site_supports_domain(site: SurfaceMoleculeSpec, domain: str | None) -> bool:
    if domain is None:
        return "unknown" in site.membrane_domains
    if "all" in site.membrane_domains:
        return True
    if domain == "unknown":
        return "unknown" in site.membrane_domains
    return domain in site.membrane_domains


def _pair_matches(
    relation: SpatialPairRelation,
    profile_a: BodySurfaceProfile,
    profile_b: BodySurfaceProfile,
) -> tuple[MolecularPairMatch, ...]:
    matches: list[MolecularPairMatch] = []
    for site_a in profile_a.molecules:
        for site_b in profile_b.molecules:
            if (
                site_b.id not in site_a.compatible_partner_ids
                or site_a.id not in site_b.compatible_partner_ids
            ):
                continue
            domain_compatible = (
                _site_supports_domain(site_a, relation.membrane_domain_a)
                and _site_supports_domain(site_b, relation.membrane_domain_b)
            )
            pair_key = frozenset((site_a.id, site_b.id))
            matches.append(MolecularPairMatch(
                molecule_a_id=site_a.id,
                molecule_b_id=site_b.id,
                pathway_ids=_MOLECULAR_PAIR_PATHWAYS.get(pair_key, ()),
                transport_programs=tuple(dict.fromkeys(
                    program
                    for program in (site_a.transport_program, site_b.transport_program)
                    if program is not None
                )),
                required_cofactor_ids=tuple(dict.fromkeys((*site_a.required_cofactor_ids, *site_b.required_cofactor_ids))),
                domain_compatible=domain_compatible,
                local_patch_presence_observed=None,
                orientation_compatible=None,
                source_ids=tuple(dict.fromkeys((*site_a.source_ids, *site_b.source_ids, "huang2010_two_dimensional_binding"))),
            ))
    return tuple(matches)


def evaluate_contact_event_chains(
    world: SpatialWorldState,
    profiles: tuple[BodySurfaceProfile, ...],
) -> tuple[ContactEventChain, ...]:
    """Evaluate deterministic gates without creating binding or transport rates."""

    profile_by_body = {profile.body_id: profile for profile in profiles}
    chains: list[ContactEventChain] = []
    for relation in world.pair_relations:
        blockers: list[str] = []
        profile_a = profile_by_body.get(relation.body_a)
        profile_b = profile_by_body.get(relation.body_b)
        matches = () if profile_a is None or profile_b is None else _pair_matches(relation, profile_a, profile_b)
        domain_matches = tuple(match for match in matches if match.domain_compatible)
        candidate_pathways = tuple(dict.fromkeys(
            pathway_id for match in domain_matches for pathway_id in match.pathway_ids
        )) if relation.geometric_contact else ()
        transport_programs = tuple(dict.fromkeys(
            program for match in domain_matches for program in match.transport_programs
        )) if relation.geometric_contact else ()
        emitted_events: list[str] = []
        if relation.contact_event != "none":
            emitted_events.append(f"geometry_contact_{relation.contact_event}")

        if not relation.geometric_contact:
            geometry_status = "closed_surfaces_separated"
            recognition_status = "inactive_without_geometric_contact"
            signaling_status = "inactive_without_molecular_binding"
            transport_status = "inactive_without_molecular_binding"
            blockers.append("surfaces are not in geometric contact")
        else:
            geometry_status = "open_engine_contact_patch_input"
            if profile_a is None:
                blockers.append(f"{relation.body_a} has no explicit molecular surface profile")
            if profile_b is None:
                blockers.append(f"{relation.body_b} has no explicit molecular surface profile")
            if profile_a is None or profile_b is None:
                recognition_status = "blocked_surface_profile_missing"
            elif not matches:
                recognition_status = "closed_no_documented_complementary_molecular_pair"
                blockers.append("no documented complementary receptor-ligand, adhesion, or channel pair")
            elif not domain_matches:
                recognition_status = "closed_molecules_outside_contacting_membrane_domains"
                blockers.append("documented molecular pair is not assigned to the contacting membrane domains")
            else:
                recognition_status = "candidate_pair_domain_compatible_patch_occupancy_and_orientation_unresolved"
                emitted_events.append("molecular_match_candidate")
                blockers.extend((
                    "local contact-patch molecule presence is not measured",
                    "molecular orientation and steric compatibility at the patch are not modeled",
                    "receptor and ligand surface densities are unavailable",
                    "two-dimensional on/off kinetics are unavailable",
                ))
            signaling_status = "blocked_until_bound_complex_and_pathway_kinetics_are_resolved"
            transport_status = "blocked_until_recognition_cofactors_and_membrane_transport_program_are_resolved"
            blockers.extend((
                "no validated bound-complex-to-signal execution law is attached",
                "no validated membrane topology-change or cargo-flux execution law is attached",
            ))

        source_ids = tuple(dict.fromkeys(
            source_id
            for match in matches
            for source_id in match.source_ids
        ))
        chains.append(ContactEventChain(
            contact_id=relation.id,
            contact_event=relation.contact_event,
            body_a=relation.body_a,
            body_b=relation.body_b,
            body_a_kind=relation.body_a_kind,
            body_b_kind=relation.body_b_kind,
            geometric_contact=relation.geometric_contact,
            geometry_gate_status=geometry_status,
            membrane_domain_a=relation.membrane_domain_a,
            membrane_domain_b=relation.membrane_domain_b,
            contact_patch_area_available=relation.contact_patch_area_um2 is not None,
            molecular_matches=matches,
            candidate_pathway_ids=candidate_pathways,
            receptor_ligand_density_available=False,
            two_dimensional_kinetics_available=False,
            molecular_recognition_status=recognition_status,
            signaling_status=signaling_status,
            transport_status=transport_status,
            transport_programs=transport_programs,
            emitted_events=tuple(emitted_events),
            may_drive_cell_state=False,
            blockers=tuple(dict.fromkeys(blockers)),
            source_ids=source_ids,
        ))
    return tuple(chains)


def compute_contact_geometry(
    cell_a: CellGeometry,
    cell_b: CellGeometry,
    *,
    candidate_pathway_ids: tuple[str, ...] = (),
) -> ContactGeometry:
    """Calculate legacy sphere proximity for isolated compatibility tests.

    A non-positive surface gap is a geometric contact candidate.  Real contact
    patch area depends on deformation, adhesion and mechanics, so it remains
    unknown even when idealized spheres overlap. Production communication state
    is adapted from :class:`SpatialWorldState` by
    :func:`contact_geometry_from_spatial_world` instead.
    """

    if cell_a.id == cell_b.id:
        raise ValueError("contact geometry requires two distinct cells")
    if cell_a.radius_um <= 0 or cell_b.radius_um <= 0:
        raise ValueError("cell radii must be positive")
    center_distance = dist(cell_a.center_um, cell_b.center_um)
    summed_radii = cell_a.radius_um + cell_b.radius_um
    surface_gap = center_distance - summed_radii
    overlap = max(0.0, -surface_gap)
    return ContactGeometry(
        id=f"{cell_a.id}__{cell_b.id}",
        cell_a=cell_a.id,
        cell_b=cell_b.id,
        center_distance_um=center_distance,
        summed_radii_um=summed_radii,
        surface_gap_um=surface_gap,
        overlap_depth_um=overlap,
        geometric_contact=surface_gap <= 0.0,
        contact_event="enter" if surface_gap <= 0.0 else "none",
        contact_input_active=surface_gap <= 0.0,
        contact_face_a_id=None,
        contact_face_b_id=None,
        membrane_domain_a=None,
        membrane_domain_b=None,
        contact_patch_polygon_um=(),
        contact_patch_area_um2=None,
        contact_patch_status="unknown_requires_deformable_cell_and_adhesion_model",
        candidate_pathway_ids=candidate_pathway_ids,
    )


def build_reference_contact_geometry() -> tuple[tuple[CellGeometry, ...], tuple[ContactGeometry, ...]]:
    """Build a legacy mathematical test fixture, not production scene state."""

    radius_um = CELL_DIAMETER_UM / 2.0
    cells = (
        CellGeometry("reference_hepatocyte_A", "hepatocyte", (0.0, 0.0, 0.0), radius_um, "sphere", "canonical_diameter_mathematical_reference"),
        CellGeometry("reference_hepatocyte_B", "hepatocyte", (CELL_DIAMETER_UM, 0.0, 0.0), radius_um, "sphere", "exact_tangent_geometry_not_observed_position"),
        CellGeometry("reference_hepatocyte_C", "hepatocyte", (0.0, CELL_DIAMETER_UM * 2.0, 0.0), radius_um, "sphere", "noncontact_geometry_not_observed_position"),
    )
    direct = tuple(pathway.id for pathway in build_hepatocyte_communication_atlas() if pathway.contact_required)
    contacts = tuple(
        compute_contact_geometry(cells[i], cells[j], candidate_pathway_ids=direct)
        for i in range(len(cells))
        for j in range(i + 1, len(cells))
    )
    return cells, contacts


def contact_geometry_from_spatial_world(
    world: SpatialWorldState,
    *,
    candidate_pathways_by_contact: dict[str, tuple[str, ...]] | None = None,
) -> tuple[tuple[CellGeometry, ...], tuple[ContactGeometry, ...]]:
    """Adapt every authoritative body pair to the communication gate.

    ``radius_um`` is retained as an equivalent-size display field for convex
    bodies; contact classification and patch geometry always come from the
    authoritative spatial relation rather than this display radius.
    """

    pathway_map = candidate_pathways_by_contact or {}
    cells: list[CellGeometry] = []
    for body in world.bodies:
        if body.shape.kind == "convex_polyhedron":
            radius_um = body.shape.equivalent_sphere_radius_um
        elif body.shape.kind == "capsule":
            radius_um = body.shape.radius_um + body.shape.half_segment_length_um
        else:
            radius_um = body.shape.radius_um
        cells.append(
            CellGeometry(
                id=body.id,
                cell_type=body.biological_kind,
                center_um=body.center_um,
                radius_um=radius_um,
                shape_kind=body.shape.kind,
                geometry_status=body.geometry_evidence,
            )
        )
    cell_ids = {cell.id for cell in cells}
    contacts: list[ContactGeometry] = []
    for relation in world.pair_relations:
        if relation.body_a not in cell_ids or relation.body_b not in cell_ids:
            continue
        contacts.append(ContactGeometry(
            id=relation.id,
            cell_a=relation.body_a,
            cell_b=relation.body_b,
            center_distance_um=relation.center_distance_um,
            summed_radii_um=(
                next(cell.radius_um for cell in cells if cell.id == relation.body_a)
                + next(cell.radius_um for cell in cells if cell.id == relation.body_b)
            ),
            surface_gap_um=relation.surface_gap_um,
            overlap_depth_um=relation.overlap_depth_um,
            geometric_contact=relation.geometric_contact,
            contact_event=relation.contact_event,
            contact_input_active=relation.contact_input_active,
            contact_face_a_id=relation.contact_face_a_id,
            contact_face_b_id=relation.contact_face_b_id,
            membrane_domain_a=relation.membrane_domain_a,
            membrane_domain_b=relation.membrane_domain_b,
            contact_patch_polygon_um=relation.contact_patch_polygon_um,
            contact_patch_area_um2=relation.contact_patch_area_um2,
            contact_patch_status=relation.contact_patch_status,
            candidate_pathway_ids=pathway_map.get(relation.id, ()),
            closest_point_a_um=relation.closest_point_a_um,
            closest_point_b_um=relation.closest_point_b_um,
            normal_a_to_b=relation.normal_a_to_b,
            relative_normal_velocity_um_s=relation.relative_normal_velocity_um_s,
            normal_load_nN=relation.normal_load_nN,
            force_status=relation.force_status,
        ))
    return tuple(cells), tuple(contacts)


def evaluate_signal_chain(
    exposure: SignalExposure,
    *,
    pathways: tuple[CommunicationPathway, ...] | None = None,
    contacts: tuple[ContactGeometry, ...] = (),
) -> SignalChainEvaluation:
    """Evaluate data sufficiency; never manufacture an activation value."""

    atlas = pathways or build_hepatocyte_communication_atlas()
    pathway_by_id = {pathway.id: pathway for pathway in atlas}
    if exposure.pathway_id not in pathway_by_id:
        raise ValueError(f"unknown communication pathway: {exposure.pathway_id}")
    pathway = pathway_by_id[exposure.pathway_id]
    contact_by_id = {contact.id: contact for contact in contacts}
    blockers: list[str] = []
    geometry_gate: bool | None = None
    local_surface_gate: bool | None = None
    local_surface_gate_status = "not_required_for_noncontact_pathway"

    if pathway.contact_required:
        if exposure.contact_id is None:
            blockers.append("contact pathway requires an explicit contact geometry record")
            geometry_gate = False
            local_surface_gate = False
            local_surface_gate_status = "closed_no_contact_record"
        elif exposure.contact_id not in contact_by_id:
            blockers.append("referenced contact geometry record is unavailable")
            geometry_gate = False
            local_surface_gate = False
            local_surface_gate_status = "closed_contact_record_unavailable"
        else:
            contact = contact_by_id[exposure.contact_id]
            geometry_gate = contact.contact_input_active
            if not geometry_gate:
                blockers.append("cell surfaces are not in geometric contact")
                local_surface_gate = False
                local_surface_gate_status = "closed_surfaces_not_in_contact"
            elif pathway.id not in contact.candidate_pathway_ids:
                geometry_gate = False
                local_surface_gate = False
                local_surface_gate_status = "closed_membrane_domain_incompatible"
                blockers.append("contacting membrane domains are incompatible with this pathway")
            else:
                patch_gates = (
                    exposure.local_receptor_or_junction_present,
                    exposure.ligand_or_partner_match_at_patch,
                    exposure.orientation_compatible_at_patch,
                )
                if any(gate is False for gate in patch_gates):
                    local_surface_gate = False
                    local_surface_gate_status = "closed_explicit_local_mismatch"
                    blockers.append("at least one local receptor/partner/orientation gate is explicitly closed")
                elif all(gate is True for gate in patch_gates):
                    local_surface_gate = True
                    local_surface_gate_status = "open_local_contact_requirements_observed"
                else:
                    local_surface_gate = None
                    local_surface_gate_status = "unknown_local_contact_requirements_not_measured"
                    blockers.append(
                        "local contact-patch receptor/junction presence, partner match, or orientation is unavailable"
                    )

    ligand_available = exposure.ligand_value is not None and exposure.ligand_unit is not None
    receptor_available = (
        exposure.receptor_surface_abundance is not None
        and exposure.receptor_abundance_unit is not None
    )
    if pathway.extracellular_exposure_required and not ligand_available:
        blockers.append("matched extracellular ligand exposure is unavailable")
    if not receptor_available:
        blockers.append("receiver surface receptor/channel abundance is unavailable")
    if not exposure.matched_downstream_response_available:
        blockers.append("matched intracellular response trajectory is unavailable")
    elif not exposure.matched_response_ids:
        blockers.append("matched response is asserted but no observation record is linked")
    if not pathway.quantitative_kinetics_available:
        blockers.append("quantitative receptor/junction kinetics are not curated")

    return SignalChainEvaluation(
        exposure_id=exposure.id,
        pathway_id=pathway.id,
        status="blocked_insufficient_quantitative_context" if blockers else "ready_for_quantitative_execution",
        mechanism_supported=True,
        geometry_gate_passed=geometry_gate,
        local_surface_gate_passed=local_surface_gate,
        local_surface_gate_status=local_surface_gate_status,
        ligand_measurement_available=ligand_available,
        receptor_measurement_available=receptor_available,
        matched_response_available=exposure.matched_downstream_response_available,
        predicted_receptor_activation=None,
        predicted_downstream_response=None,
        may_drive_cell_state=False,
        matched_response_ids=exposure.matched_response_ids,
        source_ids=exposure.source_ids,
        blockers=tuple(dict.fromkeys(blockers)),
    )


def build_hepatocyte_communication_system(
    spatial_world: SpatialWorldState | None = None,
) -> HepatocyteCommunicationSystem:
    pathways = build_hepatocyte_communication_atlas()
    active_world = spatial_world or build_single_hepatocyte_world()
    surface_profiles = build_body_surface_profiles(active_world)
    contact_chains = evaluate_contact_event_chains(active_world, surface_profiles)
    cells, contacts = contact_geometry_from_spatial_world(
        active_world,
        candidate_pathways_by_contact={
            chain.contact_id: chain.candidate_pathway_ids
            for chain in contact_chains
        },
    )
    phh_validation = load_healthy_phh_glucose_validation()
    measured_response_ids = tuple(item.id for item in phh_validation.insulin_response_observations)
    insulin_evaluation = evaluate_signal_chain(
        SignalExposure(
            id="kemas_insulin_sensitive_phh_spheroid_challenge",
            pathway_id="insulin_insr_pi3k_akt",
            sender_id="defined_culture_medium",
            receiver_id="insulin_sensitive_primary_human_hepatocyte_3d_spheroids",
            ligand_value=1_700_000.0,
            ligand_unit="pM_insulin",
            receptor_surface_abundance=None,
            receptor_abundance_unit=None,
            matched_downstream_response_available=True,
            matched_response_ids=measured_response_ids,
            source_ids=("kemas2021_phh_glucose",),
        ),
        pathways=pathways,
    )
    system = HepatocyteCommunicationSystem(
        version="hepatocyte_intercellular_communication_v4",
        species="Homo sapiens",
        cell_type="adult hepatocyte reference",
        status="engine_geometry_molecular_match_signal_transport_fail_closed",
        pathways=pathways,
        reference_cells=cells,
        reference_contacts=contacts,
        body_surface_profiles=surface_profiles,
        contact_event_chains=contact_chains,
        evaluated_exposures=(insulin_evaluation,),
        measured_exposure_count=1,
        matched_response_evidence_count=len(measured_response_ids),
        quantitative_pathway_count=sum(pathway.quantitative_kinetics_available for pathway in pathways),
        active_signal_count=0,
        recognition_candidate_count=sum(
            chain.molecular_recognition_status.startswith("candidate_")
            for chain in contact_chains
        ),
        active_transport_count=0,
        automatic_state_coupling=False,
        event_chain_contract=(
            "engine geometry enter/stay/exit -> explicit complementary surface molecules and membrane domains -> "
            "local patch presence plus orientation plus 2D density/kinetics -> pathway activation -> separately "
            "validated membrane transport; any unknown gate blocks downstream state changes"
        ),
        reference_geometry_is_biological_observation=False,
        limitations=(
            "The pathway graph records supported mechanism direction, not a measured state of the simulated cell.",
            "The normal scenario contains one hepatocyte; additional bodies must be supplied by an explicit interaction scenario.",
            "Contact enter/stay switches geometry input on and exit switches it off; downstream persistence requires its own pathway kinetics.",
            "Soluble hormones are concentration/exposure fields, never cell-scale collision projectiles.",
            "A body-level receptor or ligand identity creates only a molecular match candidate; local patch occupancy and orientation remain separate gates.",
            "Lateral-lateral geometric contact is necessary but not sufficient for cadherin or gap-junction activation.",
            "HBV uses its measured-scale collision body only in explicit scenarios; NTCP attachment cannot trigger entry without an independently resolved EGFR/endocytosis gate.",
            "One defined PHH-spheroid insulin exposure has measured pAKT and gene-expression responses, but INSR surface abundance and quantitative kinetics remain unavailable.",
            "Ligand exposure, surface abundance, receptor occupancy, junction permeability and matched downstream trajectories remain required for every simulated context.",
        ),
    )
    validate_hepatocyte_communication_system(system)
    return system


def validate_hepatocyte_communication_system(system: HepatocyteCommunicationSystem) -> None:
    source_ids = set(COMMUNICATION_SOURCES)
    if system.species != "Homo sapiens":
        raise ValueError("communication atlas must retain its human target species")
    if system.automatic_state_coupling or system.active_signal_count or system.active_transport_count:
        raise ValueError("uncalibrated communication atlas cannot activate cell state")
    if system.quantitative_pathway_count:
        raise ValueError("no communication pathway currently has complete quantitative kinetics")
    if system.measured_exposure_count != 1 or system.matched_response_evidence_count != 3:
        raise ValueError("curated PHH insulin-response evidence is missing")
    if len(system.evaluated_exposures) != 1:
        raise ValueError("unexpected communication exposure evaluation count")
    insulin_evaluation = system.evaluated_exposures[0]
    if (
        insulin_evaluation.pathway_id != "insulin_insr_pi3k_akt"
        or not insulin_evaluation.ligand_measurement_available
        or insulin_evaluation.receptor_measurement_available
        or not insulin_evaluation.matched_response_available
        or insulin_evaluation.predicted_receptor_activation is not None
        or insulin_evaluation.predicted_downstream_response is not None
        or insulin_evaluation.may_drive_cell_state
        or set(insulin_evaluation.matched_response_ids)
        != {"kemas_insulin_pakt_ser473_7min", "kemas_insulin_pck1_6h", "kemas_insulin_g6pc_6h"}
        or set(insulin_evaluation.source_ids) != {"kemas2021_phh_glucose"}
    ):
        raise ValueError("measured PHH insulin response exceeded or lost its evidence boundary")
    if system.reference_geometry_is_biological_observation:
        raise ValueError("mathematical reference geometry cannot be labeled as an observation")
    if len(system.pathways) != 8:
        raise ValueError("hepatocyte communication atlas is incomplete")
    for pathway in system.pathways:
        if pathway.automatic_state_coupling or pathway.quantitative_kinetics_available:
            raise ValueError(f"pathway {pathway.id} exceeds current evidence")
        if not pathway.source_ids or not set(pathway.source_ids) <= source_ids:
            raise ValueError(f"pathway {pathway.id} lacks registered provenance")
        if not pathway.steps:
            raise ValueError(f"pathway {pathway.id} has no mechanism steps")
        for step in pathway.steps:
            if not step.source_ids or not set(step.source_ids) <= source_ids:
                raise ValueError(f"pathway step {step.upstream}->{step.downstream} lacks provenance")
    cell_ids = {cell.id for cell in system.reference_cells}
    profile_ids = {profile.body_id for profile in system.body_surface_profiles}
    if not profile_ids <= cell_ids:
        raise ValueError("surface profile references an unknown spatial body")
    for profile in system.body_surface_profiles:
        if not profile.molecules:
            raise ValueError(f"surface profile {profile.profile_id} has no molecules")
        for molecule in profile.molecules:
            if (
                molecule.surface_abundance_per_um2 is not None
                or molecule.kon_2d_um2_per_molecule_s is not None
                or molecule.koff_s is not None
                or molecule.patch_distribution_available
                or molecule.orientation_model_available
            ):
                raise ValueError(f"surface molecule {molecule.id} exceeds current quantitative evidence")
            if not molecule.source_ids or not set(molecule.source_ids) <= source_ids:
                raise ValueError(f"surface molecule {molecule.id} lacks registered provenance")

    chain_by_contact = {chain.contact_id: chain for chain in system.contact_event_chains}
    if len(chain_by_contact) != len(system.contact_event_chains):
        raise ValueError("contact event-chain ids must be unique")
    expected_candidates = sum(
        chain.molecular_recognition_status.startswith("candidate_")
        for chain in system.contact_event_chains
    )
    if system.recognition_candidate_count != expected_candidates:
        raise ValueError("molecular recognition candidate count is inconsistent")
    if system.active_transport_count != 0:
        raise ValueError("unvalidated membrane transport cannot be active")
    for chain in system.contact_event_chains:
        if chain.may_drive_cell_state:
            raise ValueError("contact gate audit cannot drive cell state")
        if chain.geometric_contact and chain.geometry_gate_status != "open_engine_contact_patch_input":
            raise ValueError("geometric contact must open exactly the geometry gate")
        if not chain.geometric_contact and chain.candidate_pathway_ids:
            raise ValueError("separated bodies cannot expose contact-pathway candidates")
        if chain.two_dimensional_kinetics_available or chain.receptor_ligand_density_available:
            raise ValueError("contact binding inputs are not identified for this release")

    for contact in system.reference_contacts:
        if contact.cell_a not in cell_ids or contact.cell_b not in cell_ids:
            raise ValueError("contact references an unknown cell")
        if contact.contact_input_active != contact.geometric_contact:
            raise ValueError("communication contact input must mirror spatial geometry")
        if contact.contact_patch_area_um2 is not None and len(contact.contact_patch_polygon_um) < 3:
            raise ValueError("resolved contact area requires a polygonal patch")
        chain = chain_by_contact.get(contact.id)
        if chain is None or chain.candidate_pathway_ids != contact.candidate_pathway_ids:
            raise ValueError("contact pathway candidates must come from the molecular event chain")
        direct_cell_pathways = {"cdh1_adherens_contact", "gjb1_connexin32_gap_junction"}
        if direct_cell_pathways.intersection(contact.candidate_pathway_ids) and (
            contact.membrane_domain_a != "lateral" or contact.membrane_domain_b != "lateral"
        ):
            raise ValueError("direct hepatocyte pathways require a lateral-lateral interface")
        if "hbv_pres1_ntcp_egfr_entry" in contact.candidate_pathway_ids and "basolateral" not in (
            contact.membrane_domain_a,
            contact.membrane_domain_b,
        ):
            raise ValueError("HBV-NTCP candidate requires a basolateral hepatocyte interface")


def hepatocyte_communication_snapshot(
    spatial_world: SpatialWorldState | None = None,
) -> dict[str, object]:
    return build_hepatocyte_communication_system(spatial_world).to_dict()
