"""Scientific authority audit for model surfaces exposed by the snapshot."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


AuditStatus = Literal["source_backed", "derived", "schematic", "blocked", "disabled"]


@dataclass(frozen=True)
class ModelSurfaceAudit:
    id: str
    status: AuditStatus
    default_snapshot_role: str
    drives_scientific_validation: bool
    action: str
    source_ids: tuple[str, ...]
    limitations: str


MODEL_SURFACE_AUDIT: tuple[ModelSurfaceAudit, ...] = (
    ModelSurfaceAudit("phh_glycogen_contexts", "source_backed", "authoritative_research_preview", True, "retain source-specific fed, postabsorptive and prolonged-fast aggregate contexts", ("human_liver_glycogen_mixed_meal_2000", "human_liver_glycogen_overnight_1996", "human_liver_glycogen_starvation_1973"), "Whole-liver glycogen contexts are not donor-, zone- or single-cell-resolved PHH measurements."),
    ModelSurfaceAudit("aggregate_energy_redox_observations", "source_backed", "denominator_preserved_reference_only", True, "retain ATP, ADP, AMP, energy charge, NAD+, total glutathione and apparent Pi-to-ATP exchange in their original assays; prohibit organelle allocation and kinetic fitting", ("human_liver_adenylates_1992", "human_liver_atp_synthesis_2008", "human_liver_glutathione_1980"), "Whole-liver and original-protein-denominator observations do not identify compartment concentrations, mitochondrial ATP synthesis, cellular ATP demand or reaction rates."),
    ModelSurfaceAudit("compartmental_energy_redox_contract", "derived", "source_backed_structural_contract", True, "retain separate cytosolic, mitochondrial-intermembrane-space, mitochondrial-matrix, ER-lumen and peroxisomal pools plus source-supported transport/process topology; keep every unmeasured value and rate null", ("cimadamore2023_slc25a4_exchange", "choudhary2014_vdac_transport", "mayr2007_slc25a3_phosphate", "wang2021_slc25a39_mitochondrial_gsh", "yong2019_slc35b1_er_atp", "lewis2014_compartmental_nadph", "hwang1992_er_glutathione", "kappenberg2022_phh_oxygen_consumption", "human_hepatocyte_proteome_2016"), "The topology is not a numerical PHH model. Aggregate tissue values and total protein groups cannot initialize organelle states, local active concentrations, fluxes or kinetics."),
    ModelSurfaceAudit("energy_redox_calibration_validation_gate", "derived", "numerical_activation_firewall", True, "audit all nine legacy ATP/redox/OXPHOS reactions as placeholders; require matched compartments, observability, donor-disjoint validation and uncertainty before fitting or state coupling", ("human_liver_adenylates_1992", "human_liver_atp_synthesis_2008", "human_liver_glutathione_1980", "human_hepatocyte_proteome_2016"), "One apparent exchange measurement permits a future same-assay comparison only. It does not identify any of the nine legacy numerical reactions, and no current energy/redox parameter is fit-eligible or predictive."),
    ModelSurfaceAudit("external_validation_readiness_program", "derived", "context_of_use_claim_and_independence_contract", True, "retain four explicit contexts of use, ten claim-level review contracts, six reviewer roles, conflict and donor-separation rules, and a staged external-review protocol; keep biological accuracy null and predictive claims disabled until signed result artifacts exist", ("fda2023_computational_model_credibility", "biomodels_submission_curation_guidance", "human_cell_atlas_liver_network", "easl_basic_science_task_force"), "The program prepares external review but contains zero independent review reports, zero same-assay validated claims, zero prospective wet-lab results and zero independent reproductions. Network or repository listings are routes to reviewers, not endorsements."),
    ModelSurfaceAudit("postabsorptive_glucose_boundary", "source_backed", "authoritative_research_preview", True, "retain", ("hmdb_2022", "human_hepatic_transit_1996"), "Systemic plasma target and whole-liver transit time do not resolve portal/arterial mixing or one sinusoid."),
    ModelSurfaceAudit("human_hepatocyte_zonation_context", "source_backed", "source_backed_reference_context", True, "retain categorical marker direction, measured protein gradients and controlled human-MPS oxygen context; block in-situ pO2 and numeric flux scaling", ("human_liver_spatial_atlas_2026", "weiss2026_spatial_proteome", "human_liver_cell_atlas_2019", "human_liver_mps_oxygen_zonation_2017"), "Human atlas marker directions and normalized protein gradients are not donor-specific absolute expression or rate multipliers. The 3-13% oxygen values are controlled MPS settings, not in-situ human sinusoidal pO2 or reaction-rate effect sizes."),
    ModelSurfaceAudit("human_liver_open_atlas", "source_backed", "cross_assay_observation_atlas", True, "retain checksummed human morphometry, surface identities, spatial protein gradients and ranked interaction hypotheses; prohibit cross-assay synthetic-donor fusion, 3D replacement, density or kinetic imputation, flux scaling and score-driven signaling", ("fabyan2026_liver_3d", "watson2025_human_liver_source_data", "watson2025_cellphonedb", "mallanna2016_phh_surfaceome", "weiss2026_spatial_proteome"), "The source layers come from different cohorts and assays. Two-dimensional area is not cell volume, cell-surface capture is not density or domain, normalized proteomics is not absolute abundance, and CellPhoneDB score is not binding probability or a kinetic rate."),
    ModelSurfaceAudit("human_hepatocyte_3d_morphometry", "source_backed", "aggregate_normal_control_geometry_reference", True, "initialize the reference cell volume and aggregate healthy lipid-droplet display fraction; preserve all mesh, shape-distribution, domain-area, organelle-distribution and contact-ground-truth gates", ("segovia_miranda2019_human_liver_3d_morphometry",), "The source reports aggregate median/MAD summaries across five normal-control reconstructions, not raw individual-cell meshes. The 11278-cell analysis pools healthy and disease groups. The active 5657.07116 um3 median is not averaged with the conflicting 2850 um3 historical stereology estimate."),
    ModelSurfaceAudit("sinusoid_glucose_homeostasis_v2", "source_backed", "authoritative_research_preview", True, "retain perfusion relaxation; block blood-cell and zonal flux", ("hmdb_2022", "human_hepatic_transit_1996"), "Whole-liver transit and systemic fasting glucose do not identify one sinusoid volume, GLUT2 exchange capacity or zone-specific cellular flux."),
    ModelSurfaceAudit("human_nutritional_homeostasis_v3", "source_backed", "organ_scale_validation_trajectory", True, "retain measured trajectory; prohibit per-cell allocation", ("human_mixed_meal_homeostasis_1996",), "Healthy-human mixed-meal glycogen and hepatic-output observations are whole-liver cohort averages, not single-cell or zone-resolved fluxes."),
    ModelSurfaceAudit("human_hepatic_flux_evidence_bundle", "source_backed", "organ_scale_reference_only", False, "use only for scale-matched validation; never initialize per-cell flux", (), "Thirty-one literature records span organ, splanchnic and whole-body scopes; portal-resolved healthy and single-hepatocyte flux are unavailable."),
    ModelSurfaceAudit("unified_nutritional_context", "source_backed", "authoritative_research_preview", True, "select source-backed glycogen profile and preserve boundary missingness", ("human_liver_glycogen_mixed_meal_2000", "human_liver_glycogen_overnight_1996", "human_liver_glycogen_starvation_1973"), "Organ flux observations have heterogeneous methods, units and scopes; they are retained separately and never averaged into per-cell rates."),
    ModelSurfaceAudit("human_endocrine_glycogen_context", "source_backed", "observation_and_validation_target", True, "retain measured peripheral trajectory and causal clamp benchmark", ("human_mixed_meal_endocrine_1996", "human_glycogen_hormone_clamp_1996"), "Mixed-meal hormones are peripheral plasma measurements; glycogen responses are liver-scale and do not identify receptor activity or per-cell kinetics."),
    ModelSurfaceAudit("human_mixed_meal_validation_protocol", "source_backed", "scale_matched_validation_protocol", True, "compare only exact measured point/window, unit and biological scale; do not interpolate or derive a pass threshold from SEM", ("human_mixed_meal_endocrine_1996", "human_mixed_meal_homeostasis_1996"), "Study A liver glycogen and Study B endocrine/output observations use the same meal protocol but different participants; no cross-arm donor matching or mechanistic boundary activation is allowed."),
    ModelSurfaceAudit("healthy_phh_spheroid_glucose_validation", "source_backed", "same_format_validation_targets", True, "retain 16 measured mean-plus-SD windows and three insulin responses; compare only against a matched PHH 3D-spheroid protocol", ("kemas2021_phh_glucose", "honka2018_human_liver_glucose_uptake", "wilson2003_human_hepatocellularity"), "The PHH observations are net medium-glucose disappearance in two-donor 3D spheroids. Wilson hepatocellularity supports a contextual organ-to-cell denominator, not single-cell geometry or direct state initialization."),
    ModelSurfaceAudit("phh_spheroid_glucose_validation_protocol", "derived", "source_locked_exact_protocol_validation", True, "retain source-locked method metadata, 12 non-overlapping cumulative-mean targets and four descriptive overlap audits; reject mismatched scale, unit, denominator, exposure or window matrices", ("kemas2021_phh_glucose",), "The paper does not identify the post-medium-change initial volume, remaining-volume schedule, volumetric factor, window-specific viable-cell count or covariance. Medium concentration reconstruction, pooled cumulative SD and pass/fail remain disabled."),
    ModelSurfaceAudit("phh_glucose_observability_gate", "derived", "measurement_operator_and_identifiability_contract", True, "project only exact signed cumulative model outputs into the 16 protocol windows; keep nine mechanism-specific fluxes and all kinetic parameters unidentified", ("kemas2021_phh_glucose", "koenig2012_hepatic_glucose_model", "grankvist2024_human_liver_fluxomics"), "The assay observes net medium glucose disappearance, not inward/outward transport or intracellular pathway allocation. Supplemental donor signs are qualitative, window-specific viable-cell counts are unavailable, and the isotope-tracing study supplies a future measurement design rather than transferable PHH numbers."),
    ModelSurfaceAudit("exact_glucose_homeostasis_subnetwork", "derived", "source_exact_structural_contract", True, "retain the official 52-species, five-compartment, 36-reaction topology and canonical pool aliases; block numerical execution until runtime pool splits, duplicated export, lumping, compartment collapse and kinetic transfer are resolved", ("koenig2012_hepatic_glucose_model", "koenig2012_plos_dataset_s2", "koenig2012_author_executable_reencoding", "koenig2012_text_s2_kinetic_parameters"), "The official publication supplement contains zero kinetic laws. Source-exact topology does not authorize fitted per-kilogram rates, and the exploratory runtime still splits cytosolic glucose and collapses cytosolic/mitochondrial cofactors."),
    ModelSurfaceAudit("glucose_open_system_exact_assay", "derived", "non_interchangeable_boundary_and_measurement_bridge", True, "keep physiological sinusoid flow and finite PHH spheroid culture as separate contexts; accept only checksum-provenanced signed model fluxes on the exact 12 independent windows and derive the 16 assay windows without inventing volume or concentration trajectories", ("hmdb_2022", "human_hepatic_transit_1996", "kemas2021_phh_glucose"), "Whole-liver transit does not identify one sinusoid. The PHH assay does not report challenge-medium volume, remaining-volume schedule, volumetric factor or window-specific viable-cell counts, so transport coupling and concentration reconstruction remain blocked."),
    ModelSurfaceAudit("glucose_calibration_heldout_validation_gate", "derived", "descriptive_comparison_and_predictive_firewall", True, "audit all 36 active reactions and all 16 PHH windows; permit exact-protocol descriptive residuals only; require mechanism-identifying measurements, donor-resolved trajectories, donor-disjoint splits, frozen artifacts and qualified uncertainty before fitting or activation", ("kemas2021_phh_glucose", "koenig2012_hepatic_glucose_model", "koenig2012_plos_dataset_s2", "koenig2012_author_executable_reencoding", "koenig2012_text_s2_kinetic_parameters", "grankvist2024_human_liver_fluxomics"), "The current endpoint identifies one aggregate medium balance and zero reaction-specific kinetic parameters. The 12 non-overlapping rows are same-format targets, while four 0-72 h rows overlap; none is a donor-held-out result."),
    ModelSurfaceAudit("phh_albumin_secretion_observability", "derived", "measurement_operator_and_identifiability_contract", True, "retain all six Table S3 24-hour PHH ELISA means and project only exact cumulative mature-albumin model outputs through the mass-conversion operator; assign no pass threshold", ("peng2025_phh_quality_attributes", "peng2022_phh_requirements_standard", "human_hepatocyte_proteome_2016", "uniprot_p02768", "usp_human_albumin_reference_standard"), "The commercial 2D-PHH cohort is not an in-vivo reference population; Table S3 labels n=3 but not the replicate class, its cell-number denominator is not a window-specific viable-cell count, and the CSCB product criterion is not a simulation threshold."),
    ModelSurfaceAudit("phh_cyp_function_observability", "derived", "batch_resolved_same_format_diagnostic", True, "retain all 72 batch-resolved CYP SCR/MFR means; treat ten source-reported zero records as censored and compare only exact assay-matched model outputs without fitting or pass/fail", ("peng2025_phh_quality_attributes", "peng2022_phh_requirements_standard"), "Six commercial PHH batches with n=3 within-batch replicates of unspecified class do not define population variance. Raw concentration time courses, LLOQs, viable-cell trajectories, genotype and absolute CYP/POR abundances are unavailable, so transport and enzyme kinetics remain unidentified."),
    ModelSurfaceAudit("phh_biliary_excretion_observability", "derived", "paired_condition_measurement_operator", True, "retain five batch-resolved d8-TCA BEI values and apply the published paired-condition ratio only to exact sandwich-culture inputs; do not infer BSEP kinetics or assign a model pass", ("peng2025_phh_quality_attributes", "peng2022_phh_requirements_standard"), "Published BEI values combine uptake, intracellular handling, canalicular export, geometry and calcium-sensitive junction behavior. Paired A_Ca/A_CaFree values and uncertainty were not published."),
    ModelSurfaceAudit("phh_identity_heterogeneity_observability", "source_backed", "batch_resolved_product_composition_reference", True, "retain FACS marker fractions and scRNA-seq composition as separate assay surfaces; prohibit conversion of product composition into one-cell internal state or generative training", ("peng2025_phh_quality_attributes", "peng2022_phh_requirements_standard", "geo_gse289636"), "Six commercial PHH batches do not define an in-vivo population distribution. Marker-positive fractions and transcriptomic cell-type fractions are different constructs, and the published five-subset count lacks a curated donor-by-subset numeric matrix."),
    ModelSurfaceAudit("phh_absolute_proteome_budget", "derived", "static_absolute_protein_mass_reference", True, "retain the article's rounded 600 pg/reference-cell and 8.7 billion molecule headlines while exposing the supplement's per-nucleus denominator; derive compartment protein masses by arithmetic only and prohibit geometry or dynamic proteostasis coupling", ("human_hepatocyte_proteome_2016",), "The article uses a cell label while Supplementary Table 2 explicitly reports proteomic-ruler values per nucleus; they are not equivalent for binucleate hepatocytes. The 3000 um3 volume is derived from assumed 200 g/L protein, and compartment percentages are protein-mass fractions rather than geometry."),
    ModelSurfaceAudit("phh_donor_resolved_absolute_proteome", "source_backed", "static_protein_group_abundance_per_nucleus", True, "retain all 8,689 quantified target protein groups and seven donor columns without imputation; permit explicit reference-nucleus population initialization but prohibit silent gene-group collapse, per-hepatocyte relabeling, surface localization, turnover or flux coupling", ("human_hepatocyte_proteome_2016", "massive_msv000079562"), "The surgical-resection donors were not healthy volunteers. The workbook denominator is per nucleus, MaxQuant groups may contain multiple accessions or genes, and total abundance does not identify localization, active fraction or kinetics."),
    ModelSurfaceAudit("hepatocyte_transporter_inventory_bridge", "derived", "denominator_audited_abundance_reference", True, "retain direct seven-donor total BSEP and MRP2 observations per nucleus plus the independent MRP2 membrane-fraction context; block surface copies, active fraction, density, flux, and literal molecule rendering", ("human_hepatocyte_proteome_2016", "human_mrp2_abundance_2012"), "BSEP and MRP2 total copies are measured per nucleus, not per hepatocyte or canalicular surface. The independent MRP2 tissue fraction remains a separate denominator, and neither transporter has measured surface-localized or active copies."),
    ModelSurfaceAudit("human_sch_endogenous_bile_acid_compartments", "source_backed", "day7_sandwich_culture_endpoint_reference", True, "retain all vehicle and 10 uM troglitazone Table 4 means plus SD; preserve experiment-level BEI aggregation and prohibit healthy-state initialization or kinetic fitting", ("marion2013_human_sch_bile_acids",), "Four-donor day-7 sandwich culture is not in-vivo physiology. Paired-buffer values use an estimated intracellular volume, source proxy zeros are censored observations, and aggregate BEI cannot be reconstructed from group means."),
    ModelSurfaceAudit("albumin_secretory_pathway_kinetics", "blocked", "explicit_parameter_pulse_chase_only", False, "require donor-resolved PHH synthesis plus compartment-resolved ER, Golgi, medium and degradation time courses before activating a constitutive secretion model", ("peng2025_phh_quality_attributes", "lodish1983_hepg2_secretory_transit"), "The PHH ELISA endpoint identifies cumulative extracellular albumin only. Published HepG2 pulse-chase evidence supports pathway topology but cannot supply PHH translation, ER export, Golgi maturation, exocytosis or degradation rates."),
    ModelSurfaceAudit("external_phh_evidence_intake", "blocked", "manual_review_gate_only", False, "validate structure and provenance metadata, then curate each candidate against its primary source before parameter promotion", (), "A structurally valid external research bundle is not itself a curated parameter registry and cannot activate coupling automatically."),
    ModelSurfaceAudit("published_hepatic_glucose_shadow_model", "derived", "non_authoritative_shadow_prediction", False, "retain audited predictions; prohibit cell-state coupling until all publication and scale-bridge gates pass", ("koenig2012_hepatic_glucose_model", "koenig2012_plos_dataset_s2", "koenig2012_author_executable_reencoding"), "The official supplement is non-kinetic; the permissively licensed current executable re-encoding reproduces two of five precision-derived publication benchmarks and represents mean liver behavior rather than a donor or zone-resolved hepatocyte."),
    ModelSurfaceAudit("published_reaction_kinetic_transfer_audit", "derived", "equation_level_transfer_firewall", False, "retain the exhaustive 36-reaction mapping and MathML fingerprints; activate no published parameter unless stoichiometry, compartment, symbolic law, per-cell units, biological context and validation all match", ("koenig2012_hepatic_glucose_model", "koenig2012_author_executable_reencoding", "koenig2012_text_s2_kinetic_parameters"), "Twelve active reactions have related candidates and three match stoichiometry after aliases, but none matches the full symbolic law, per-cell scale and healthy-PHH context. Fitted per-kilogram Vmax values cannot be copied into the single-cell network."),
    ModelSurfaceAudit("published_hepatic_glucose_lineage_audit", "derived", "reproducibility_audit_only", False, "retain the four-way protocol matrix; never substitute the unlicensed legacy executable for the vendored runtime", ("koenig2012_hepatic_glucose_model", "koenig_glucose_model_author_repository", "koenig_glucose_glycogen_protocol_script", "koenig_glucose_glycogen_figure_script"), "The later author-repository lineage reproduces five reported targets under recovered conditions, but the repository protocol conflicts with the paper legend and exact publication-artifact equivalence remains unresolved."),
    ModelSurfaceAudit("published_glucose_external_human_validation", "derived", "diagnostic_contextual_comparison_only", False, "retain the unit-normalized HGO residual and 16 blocked PHH targets without assigning pass/fail; require matched dynamic context for validation", ("koenig2012_hepatic_glucose_model", "human_mixed_meal_endocrine_1996", "nist_glucose_molar_mass", "kemas2021_phh_glucose", "honka2018_human_liver_glucose_uptake", "wilson2003_human_hepatocellularity"), "The liver-scale model and human HGO estimate have unmatched time and boundaries. The PHH spheroid observations have no same-format model prediction, and the delivered model-only curve is not held-out human validation."),
    ModelSurfaceAudit("hepatocyte_communication_mechanism_atlas", "source_backed", "mechanism_and_measured_response_reference", False, "retain source-backed pathway topology, experimentally observed PHH surface identities and the measured PHH insulin response; use geometry only to open the first gate; require local molecule density, orientation and 2D kinetics before binding; require a separate validated signal or transport law before state coupling", ("reactome_insulin_receptor", "glucagon_creb_hepatic_control", "cajulao2022_gcgr_endocytosis", "reactome_hgf_met", "reactome_il6_signaling", "wnt_beta_catenin_liver_regeneration", "reactome_adherens_junctions", "hepatocyte_connexin32_signal_propagation", "huang2010_two_dimensional_binding", "yan2012_hbv_ntcp", "iwamoto2019_hbv_egfr", "kemas2021_phh_glucose", "mallanna2016_phh_surfaceome"), "Soluble hormones are exposure fields rather than collision bodies. Cell-surface capture supports SLC10A1, EGFR, INSR, MET, IL6ST, ABCB11, ABCC2 and ABCB1 identity but supplies no density, domain or orientation. A defined 1.7 uM insulin challenge has matched pAKT and PCK1/G6PC responses in PHH spheroids, but INSR surface abundance, receptor occupancy and complete kinetics remain unavailable. HBV preS1-NTCP attachment and EGFR-dependent internalization are separate gates; neither has project-ready PHH 2D kinetics."),
    ModelSurfaceAudit("cell_contact_geometry", "derived", "geometry_authoritative_runtime_spatial_state", False, "use engine-owned convex surfaces for signed gap, broad contact-patch geometry, membrane-domain labels, enter/stay/exit inputs and volume-preserving contact deformation; enforce the explicit 1% cross-system area-strain cap; do not use elapsed contact time as a causal parameter; keep force, adhesion, junction gating and biochemical activation blocked", ("segovia_miranda2019_human_liver_3d_morphometry", "duarte1989_human_hepatocyte_volume", "olander2021_human_hepatocyte_size", "fabyan2026_human_liver_3d", "evans1976_human_membrane_area_lysis", "rawicz2000_bilayer_elasticity", "guillou2016_membrane_surface_reservoirs"), "The canonical scale preserves the direct normal-control 3D median volume 5657.07116 um3; its 22.1071 um equivalent diameter is derived. The conflicting 2850 um3 historical stereology result and independent 18.4 um isolated-PHH median remain separate context checks. The regular truncated-octahedron boundary and affine deformation are kinematic proxies, not donor tissue morphometry or PHH rheology. One percent is an engineering cap equal to half the lower 2% human-RBC lysis bound. Computed patch area and deformation cannot identify adhesion bond density, force, stiffness, receptor occupancy or gap-junction permeability."),
    ModelSurfaceAudit("brian2_intercellular_execution", "blocked", "optional_backend_gate", False, "require the pinned backend plus source-backed equations, complete units, calibrated parameters and geometry coupling", ("brian2_2_10_1", "brian2_custom_events"), "Brian2 is an equation/event executor, not a source of hepatocyte biology. No calibrated communication model is attached."),
    ModelSurfaceAudit("generative_hepatocyte_model", "blocked", "data_and_model_governance_boundary", False, "require donor-disjoint measured data, frozen schema, weight checksum, held-out evaluation and posterior predictive checks", ("autoencoding_variational_bayes", "scvi_single_cell_generative_model", "scgen_perturbation_model", "scvi_tools_documentation"), "No audited donor-resolved training bundle or validated model artifact is loaded; synthetic candidates cannot drive the mechanistic engine."),
    ModelSurfaceAudit("normalized_pool_engine", "schematic", "legacy_relative_state", False, "never use for quantitative validation", ("project_roadmap_07",), "All 48 pools are relative 0-1 placeholders."),
    ModelSurfaceAudit("organelle_functional_cycles", "schematic", "legacy_relative_state", False, "retain only as qualitative renderer driver", ("project_roadmap_07",), "Cycle rates, error fractions, damage and repair coefficients are uncalibrated."),
    ModelSurfaceAudit("organelle_failure_hazards", "disabled", "not_executed_without_calibration", False, "require a source-tagged calibration object", (), "Former per-hour base risks and stress weights were project assumptions."),
    ModelSurfaceAudit("cytokinesis_failure_probability", "disabled", "not_executed_without_calibration", False, "require measured context-specific probability", ("human_hepatocyte_binucleation",), "Binucleated-cell prevalence cannot be used as a per-division failure probability."),
    ModelSurfaceAudit("phh_protein_functional_evidence", "source_backed", "observation_and_same_assay_comparison_only", False, "retain donor abundance, localization identity, assay kinetics, coupled whole-cell transport ranges and response timepoints as separate observables; require measured active surface copies and exact-protocol whole-cell predictions before coupling", ("human_hepatocyte_proteome_2016", "mallanna2016_phh_surfaceome", "human_bsep_taurocholate_2002", "human_bsep_taurocholate_2013", "human_mrp2_bilirubin_glucuronides_1999", "human_ntcp_uptake_2003", "bi2006_human_schh_taurocholate_transport", "kemas2021_phh_glucose"), "All eight selected proteins have seven-donor total abundance profiles. Six have PHH surface-identity evidence, three have a sourced physiological membrane domain, five transporter observations retain their original assay contexts, and three INSR-linked responses retain their measured timepoints. Bi 2006 adds five-lot coupled taurocholate apparent uptake, intrinsic biliary clearance and BEI ranges without assigning them to individual transporters. Surface copy count, active fraction, receptor binding kinetics, donor activity distributions and whole-cell protein rates remain unmeasured."),
    ModelSurfaceAudit("absolute_transporter_flux", "blocked", "qualitative_activity_only", False, "require active surface copies and matched turnover", ("human_mrp2_abundance_2012", "human_bsep_taurocholate_2013", "human_ntcp_uptake_2003"), "Total or membrane-fraction abundance is not active canalicular surface abundance. Total-copy ratios cannot automatically scale functional activity."),
    ModelSurfaceAudit("legacy_atp_turnover_kinetics", "blocked", "exploratory_software_fixture_only", False, "replace matched first-order ADP-to-ATP and ATP-to-ADP constants with compartment-resolved, mechanism-identified healthy-PHH kinetics", ("human_liver_atp_synthesis_2008",), "The 29.5 mM/min whole-liver 31P-MRS result is apparent Pi-to-ATP exchange. It does not identify mitochondrial synthesis, ATP demand or either executable first-order constant."),
    ModelSurfaceAudit("glutathione_redox_kinetics", "blocked", "exploratory_network_only", False, "require compartment-resolved human GSH/GSSG/NADPH trajectories", ("human_liver_glutathione_1980", "primary_hepatocyte_isolation_metabolism_2018"), "Legacy GPx, reductase, PPP and ROS influx rates are placeholders; isolation changes these pools."),
    ModelSurfaceAudit("legacy_oxphos_kinetics", "blocked", "exploratory_software_fixture_only", False, "require matched PHH OCR, ATP-linked respiration, compartment states, membrane potential, active complexes and held-out validation", ("oxphos_po_ratio", "kappenberg2022_phh_oxygen_consumption"), "P/O topology does not authorize the executable TCA/ETC Vmax, Km, seed pools or a single shared ATP/NAD(H) compartment."),
    ModelSurfaceAudit("integrated_reaction_authority", "derived", "reaction_level_validation_firewall", False, "audit numerical parameter provenance separately from pathway topology; allow unsupported channels only in an explicitly exploratory runtime and fail closed for quantitative validation or prediction", (), "A pathway citation does not identify the numerical rate used by the runtime. Source-backed parameterization, matched biological/experimental context and independent held-out validation are separate gates."),
    ModelSurfaceAudit("integrated_fuel_pathway_rates", "blocked", "exploratory_network_only", False, "replace pseudo-first-order magnitudes with fitted human fluxes", ("hepatic_glucose_homeostasis",), "Topology and stoichiometry are useful, but several absolute rates are illustrative."),
    ModelSurfaceAudit("endocrine_receptor_rate_coupling", "blocked", "measurement_gate_only", False, "require matched physiological exposure, receptor abundance/occupancy and dose-time response sufficient for a rate law", ("human_mixed_meal_endocrine_1996", "human_glycogen_hormone_clamp_1996", "kemas2021_phh_glucose"), "The PHH spheroid pAKT and gene-expression responses close part of the chain, but the 1.7 uM challenge is a conventional culture concentration and no INSR abundance, EC50, Hill coefficient or portal-matched kinetics is available."),
    ModelSurfaceAudit("cell_fate_thresholds", "blocked", "evidence_labels_only", False, "do not claim calibrated time-to-death", ("atp_death_switch", "human_bile_acid_death_mode"), "Relative stress thresholds are not matched human-hepatocyte commitment kinetics."),
    ModelSurfaceAudit("genome_expression", "derived", "structural_data_gated", False, "run dynamics only for calibrated genes", ("human_hepatocyte_proteome_2016",), "Reference coordinates are real; most donor expression and gene-specific kinetics are unknown."),
    ModelSurfaceAudit("hepatocyte_capability_atlas", "derived", "scope_and_activation_firewall", True, "retain one concise template for every modeled hepatocyte capability; keep every quantitative slot null until its biological scale, compartment, assay context, uncertainty and validation evidence are complete", ("macparland2018_human_liver_atlas", "thul2017_subcellular_proteome", "human1_metabolic_atlas"), "The atlas defines coverage and missing evidence, not an executable whole-cell model. A feature name or pathway source cannot authorize a parameter value."),
    ModelSurfaceAudit("cellular_memory_substrate_contract", "derived", "event_log_to_physical_memory_firewall", True, "record history events separately from persistent biological state; promote an event to memory only when a physical substrate, write mechanism, persistence test, readout and erasure or dilution mechanism are identified", ("alberts_cell_memory_substrates",), "The current event ledger is provenance, not biological memory. No substrate-specific consolidation, inheritance or future-response law is numerically calibrated."),
    ModelSurfaceAudit("reaction_evidence_atlas", "derived", "reaction_level_evidence_and_transport_firewall", True, "retain all 36 active reactions and their missing kinetic, compartment, abundance, transport, uncertainty and validation fields; execute no quantitative scientific claim from a null or merely related candidate", ("sabio_rk_kinetics_database", "brenda_enzyme_database", "hepatokin1_human_liver_model", "davidi2016_in_vivo_catalytic_rates"), "All 432 evidence slots are currently null. Twelve reactions have related published-model candidates, three match stoichiometry after aliases and none passes full symbolic, scale, compartment and healthy-PHH transfer gates."),
    ModelSurfaceAudit("cytosol_transport_rheology_contract", "derived", "dimensionless_numerics_and_biological_coupling_firewall", True, "represent cytoplasm as an aqueous mobile phase coupled to a porous viscoelastic scaffold; exercise moving-boundary pressure projection and conservative passive-scalar transport only as dimensionless numerical kernels; keep aqueous diffusion separate from ATP-dependent motor cargo and require matched healthy-PHH evidence before biological coupling", ("moeendarbary2013_poroelastic_cytoplasm", "kwapiszewska2020_cytoplasm_nanoviscosity", "swaminathan1997_gfp_cytoplasmic_diffusion", "guo2017_cytoplasm_size_speed_mechanics", "jiang2020_human_hepatocyte_diffusion_mri", "guo2014_motor_driven_cytoplasm", "fort2011_hepatocyte_connexin_kinesin_transport", "murray2008_primary_rat_hepatocyte_endosome_transport"), "The renderer has a dimensionless projection grid, moving analytic organelle boundaries and an unbound conservative scalar kernel. No healthy-PHH viscosity, pressure, intracellular velocity, species diffusivity, motor-cargo rate or reaction-transport validation is loaded, so zero biological species and zero reactions are coupled and pressure cannot feed membrane mechanics."),
    ModelSurfaceAudit("metabolic_constraint_shell", "derived", "pinned_reconstruction_and_genome_scale_activation_firewall", True, "retain the checksum-pinned Human-GEM v2.0.0 candidate artifact; require a declared PHH extraction context, measured exchange bounds, objective, solver configuration, mass/charge audit and scale-matched validation before FBA, FVA, thermodynamic or enzyme constraints can run", ("human1_metabolic_atlas", "human_gem_repository"), "The exact generic reconstruction is pinned but not vendored or loaded by runtime, and no optimization runs. A generic stoichiometric topology does not identify a healthy single-hepatocyte flux state."),
    ModelSurfaceAudit("hepatocyte_completion_matrix", "derived", "scoped_completion_and_blocker_ledger", True, "report every major engineering and evidence gap using closed, partial, blocked, external-action or scale-inapplicable status; treat closed as local to the declared scope and keep whole-cell biological accuracy null", (), "The ledger improves auditability but supplies no biological measurement, parameter, validation result or whole-cell realism percentage."),
)


def scientific_model_audit_snapshot() -> dict[str, object]:
    blocked = tuple(item.id for item in MODEL_SURFACE_AUDIT if item.status in ("blocked", "disabled"))
    authoritative = tuple(item.id for item in MODEL_SURFACE_AUDIT if item.drives_scientific_validation)
    return {
        "status": "mixed_authority_research_preview",
        "authoritative_surfaces": authoritative,
        "blocked_or_disabled_surfaces": blocked,
        "surfaces": MODEL_SURFACE_AUDIT,
        "policy": "Only source-backed observations and explicitly derived audit/measurement contracts may drive scientific validation. Schematic, blocked and disabled surfaces may not support quantitative claims.",
    }
