"""Scientific authority audit for model surfaces exposed by the snapshot."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


AuditStatus = Literal["source_backed", "derived", "schematic", "blocked", "disabled"]


@dataclass(frozen=True)
class ModelSurfaceAudit:
    id: str
    status: AuditStatus
    default_snapshot_role: str
    drives_scientific_validation: bool
    action: str
    source_ids: tuple[str, ...]
    limitations: str


MODEL_SURFACE_AUDIT: tuple[ModelSurfaceAudit, ...] = (
    ModelSurfaceAudit("phh_energy_and_glycogen", "source_backed", "authoritative_research_preview", True, "retain", ("human_liver_adenylates_1992", "human_liver_atp_synthesis_2008", "human_liver_glycogen_mixed_meal_2000", "human_liver_glycogen_overnight_1996", "human_liver_glycogen_starvation_1973"), "Whole-liver-equivalent values are not compartment-resolved isolated-PHH measurements."),
    ModelSurfaceAudit("postabsorptive_glucose_boundary", "source_backed", "authoritative_research_preview", True, "retain", ("hmdb_2022", "human_hepatic_transit_1996"), "Systemic plasma target and whole-liver transit time do not resolve portal/arterial mixing or one sinusoid."),
    ModelSurfaceAudit("human_hepatocyte_zonation_context", "source_backed", "source_backed_reference_context", True, "retain categorical marker direction and controlled human-MPS oxygen context; block in-situ pO2 and numeric flux scaling", ("human_liver_spatial_atlas_2026", "human_liver_single_cell_proteomics_2025", "human_liver_cell_atlas_2019", "human_liver_mps_oxygen_zonation_2017"), "Human atlas marker directions are not donor-specific expression values. The 3-13% oxygen values are controlled MPS settings, not in-situ human sinusoidal pO2 or reaction-rate effect sizes."),
    ModelSurfaceAudit("sinusoid_glucose_homeostasis_v2", "source_backed", "authoritative_research_preview", True, "retain perfusion relaxation; block blood-cell and zonal flux", ("hmdb_2022", "human_hepatic_transit_1996"), "Whole-liver transit and systemic fasting glucose do not identify one sinusoid volume, GLUT2 exchange capacity or zone-specific cellular flux."),
    ModelSurfaceAudit("human_nutritional_homeostasis_v3", "source_backed", "organ_scale_validation_trajectory", True, "retain measured trajectory; prohibit per-cell allocation", ("human_mixed_meal_homeostasis_1996",), "Healthy-human mixed-meal glycogen and hepatic-output observations are whole-liver cohort averages, not single-cell or zone-resolved fluxes."),
    ModelSurfaceAudit("human_hepatic_flux_evidence_bundle", "source_backed", "organ_scale_reference_only", False, "use only for scale-matched validation; never initialize per-cell flux", (), "Thirty-one literature records span organ, splanchnic and whole-body scopes; portal-resolved healthy and single-hepatocyte flux are unavailable."),
    ModelSurfaceAudit("unified_nutritional_context", "source_backed", "authoritative_research_preview", True, "select source-backed glycogen profile and preserve boundary missingness", ("human_liver_glycogen_mixed_meal_2000", "human_liver_glycogen_overnight_1996", "human_liver_glycogen_starvation_1973"), "Organ flux observations have heterogeneous methods, units and scopes; they are retained separately and never averaged into per-cell rates."),
    ModelSurfaceAudit("human_endocrine_glycogen_context", "source_backed", "observation_and_validation_target", True, "retain measured peripheral trajectory and causal clamp benchmark", ("human_mixed_meal_endocrine_1996", "human_glycogen_hormone_clamp_1996"), "Mixed-meal hormones are peripheral plasma measurements; glycogen responses are liver-scale and do not identify receptor activity or per-cell kinetics."),
    ModelSurfaceAudit("human_mixed_meal_validation_protocol", "source_backed", "scale_matched_validation_protocol", True, "compare only exact measured point/window, unit and biological scale; do not interpolate or derive a pass threshold from SEM", ("human_mixed_meal_endocrine_1996", "human_mixed_meal_homeostasis_1996"), "Study A liver glycogen and Study B endocrine/output observations use the same meal protocol but different participants; no cross-arm donor matching or mechanistic boundary activation is allowed."),
    ModelSurfaceAudit("healthy_phh_spheroid_glucose_validation", "source_backed", "same_format_validation_targets", True, "retain 16 measured mean-plus-SD windows and three insulin responses; compare only against a matched PHH 3D-spheroid protocol", ("kemas2021_phh_glucose", "honka2018_human_liver_glucose_uptake", "wilson2003_human_hepatocellularity"), "The PHH observations are net medium-glucose disappearance in two-donor 3D spheroids. Wilson hepatocellularity supports a contextual organ-to-cell denominator, not single-cell geometry or direct state initialization."),
    ModelSurfaceAudit("phh_spheroid_glucose_validation_protocol", "derived", "source_locked_exact_protocol_validation", True, "retain source-locked method metadata, 12 non-overlapping cumulative-mean targets and four descriptive overlap audits; reject mismatched scale, unit, denominator, exposure or window matrices", ("kemas2021_phh_glucose",), "The paper does not identify the post-medium-change initial volume, remaining-volume schedule, volumetric factor, window-specific viable-cell count or covariance. Medium concentration reconstruction, pooled cumulative SD and pass/fail remain disabled."),
    ModelSurfaceAudit("phh_glucose_observability_gate", "derived", "measurement_operator_and_identifiability_contract", True, "project only exact signed cumulative model outputs into the 16 protocol windows; keep nine mechanism-specific fluxes and all kinetic parameters unidentified", ("kemas2021_phh_glucose", "koenig2012_hepatic_glucose_model", "grankvist2024_human_liver_fluxomics"), "The assay observes net medium glucose disappearance, not inward/outward transport or intracellular pathway allocation. Supplemental donor signs are qualitative, window-specific viable-cell counts are unavailable, and the isotope-tracing study supplies a future measurement design rather than transferable PHH numbers."),
    ModelSurfaceAudit("phh_albumin_secretion_observability", "derived", "measurement_operator_and_identifiability_contract", True, "retain all six Table S3 24-hour PHH ELISA means and project only exact cumulative mature-albumin model outputs through the mass-conversion operator; assign no pass threshold", ("peng2025_phh_quality_attributes", "peng2022_phh_requirements_standard", "human_hepatocyte_proteome_2016", "uniprot_p02768", "usp_human_albumin_reference_standard"), "The commercial 2D-PHH cohort is not an in-vivo reference population; Table S3 labels n=3 but not the replicate class, its cell-number denominator is not a window-specific viable-cell count, and the CSCB product criterion is not a simulation threshold."),
    ModelSurfaceAudit("phh_cyp_function_observability", "derived", "batch_resolved_same_format_diagnostic", True, "retain all 72 batch-resolved CYP SCR/MFR means; treat ten source-reported zero records as censored and compare only exact assay-matched model outputs without fitting or pass/fail", ("peng2025_phh_quality_attributes", "peng2022_phh_requirements_standard"), "Six commercial PHH batches with n=3 within-batch replicates of unspecified class do not define population variance. Raw concentration time courses, LLOQs, viable-cell trajectories, genotype and absolute CYP/POR abundances are unavailable, so transport and enzyme kinetics remain unidentified."),
    ModelSurfaceAudit("phh_biliary_excretion_observability", "derived", "paired_condition_measurement_operator", True, "retain five batch-resolved d8-TCA BEI values and apply the published paired-condition ratio only to exact sandwich-culture inputs; do not infer BSEP kinetics or assign a model pass", ("peng2025_phh_quality_attributes", "peng2022_phh_requirements_standard"), "Published BEI values combine uptake, intracellular handling, canalicular export, geometry and calcium-sensitive junction behavior. Paired A_Ca/A_CaFree values and uncertainty were not published."),
    ModelSurfaceAudit("phh_identity_heterogeneity_observability", "source_backed", "batch_resolved_product_composition_reference", True, "retain FACS marker fractions and scRNA-seq composition as separate assay surfaces; prohibit conversion of product composition into one-cell internal state or generative training", ("peng2025_phh_quality_attributes", "peng2022_phh_requirements_standard", "geo_gse289636"), "Six commercial PHH batches do not define an in-vivo population distribution. Marker-positive fractions and transcriptomic cell-type fractions are different constructs, and the published five-subset count lacks a curated donor-by-subset numeric matrix."),
    ModelSurfaceAudit("phh_absolute_proteome_budget", "derived", "static_absolute_protein_mass_reference", True, "retain the seven-donor 600 pg/cell and 8.7 billion protein-molecule averages; derive compartment protein masses by arithmetic only and prohibit geometry or dynamic proteostasis coupling", ("human_hepatocyte_proteome_2016",), "Headline uncertainty is not published. The 3000 um3 volume is derived from an assumed 200 g/L protein concentration, and compartment percentages are protein-mass fractions rather than organelle volumes or membrane areas."),
    ModelSurfaceAudit("hepatocyte_transporter_inventory_bridge", "derived", "denominator_audited_abundance_reference", True, "retain the same-cohort total BSEP copy bridge; keep MRP2 in its tissue membrane-protein denominator and block surface copies, active fraction, density, flux, and literal molecule rendering", ("human_hepatocyte_proteome_2016", "human_mrp2_abundance_2012"), "The approximately 5.1e5 BSEP copies are total cellular copies in an average reference cell. MRP2 has no valid per-hepatocyte denominator bridge, and neither transporter has measured canalicular surface or active copies."),
    ModelSurfaceAudit("human_sch_endogenous_bile_acid_compartments", "source_backed", "day7_sandwich_culture_endpoint_reference", True, "retain all vehicle and 10 uM troglitazone Table 4 means plus SD; preserve experiment-level BEI aggregation and prohibit healthy-state initialization or kinetic fitting", ("marion2013_human_sch_bile_acids",), "Four-donor day-7 sandwich culture is not in-vivo physiology. Paired-buffer values use an estimated intracellular volume, source proxy zeros are censored observations, and aggregate BEI cannot be reconstructed from group means."),
    ModelSurfaceAudit("albumin_secretory_pathway_kinetics", "blocked", "explicit_parameter_pulse_chase_only", False, "require donor-resolved PHH synthesis plus compartment-resolved ER, Golgi, medium and degradation time courses before activating a constitutive secretion model", ("peng2025_phh_quality_attributes", "lodish1983_hepg2_secretory_transit"), "The PHH ELISA endpoint identifies cumulative extracellular albumin only. Published HepG2 pulse-chase evidence supports pathway topology but cannot supply PHH translation, ER export, Golgi maturation, exocytosis or degradation rates."),
    ModelSurfaceAudit("external_phh_evidence_intake", "blocked", "manual_review_gate_only", False, "validate structure and provenance metadata, then curate each candidate against its primary source before parameter promotion", (), "A structurally valid external research bundle is not itself a curated parameter registry and cannot activate coupling automatically."),
    ModelSurfaceAudit("published_hepatic_glucose_shadow_model", "derived", "non_authoritative_shadow_prediction", False, "retain audited predictions; prohibit cell-state coupling until all publication and scale-bridge gates pass", ("koenig2012_hepatic_glucose_model", "koenig2012_plos_dataset_s2", "koenig2012_author_executable_reencoding"), "The official supplement is non-kinetic; the permissively licensed current executable re-encoding reproduces two of five precision-derived publication benchmarks and represents mean liver behavior rather than a donor or zone-resolved hepatocyte."),
    ModelSurfaceAudit("published_hepatic_glucose_lineage_audit", "derived", "reproducibility_audit_only", False, "retain the four-way protocol matrix; never substitute the unlicensed legacy executable for the vendored runtime", ("koenig2012_hepatic_glucose_model", "koenig_glucose_model_author_repository", "koenig_glucose_glycogen_protocol_script", "koenig_glucose_glycogen_figure_script"), "The later author-repository lineage reproduces five reported targets under recovered conditions, but the repository protocol conflicts with the paper legend and exact publication-artifact equivalence remains unresolved."),
    ModelSurfaceAudit("published_glucose_external_human_validation", "derived", "diagnostic_contextual_comparison_only", False, "retain the unit-normalized HGO residual and 16 blocked PHH targets without assigning pass/fail; require matched dynamic context for validation", ("koenig2012_hepatic_glucose_model", "human_mixed_meal_endocrine_1996", "nist_glucose_molar_mass", "kemas2021_phh_glucose", "honka2018_human_liver_glucose_uptake", "wilson2003_human_hepatocellularity"), "The liver-scale model and human HGO estimate have unmatched time and boundaries. The PHH spheroid observations have no same-format model prediction, and the delivered model-only curve is not held-out human validation."),
    ModelSurfaceAudit("hepatocyte_communication_mechanism_atlas", "source_backed", "mechanism_and_measured_response_reference", False, "retain source-backed pathway topology and the measured PHH insulin response; require receptor abundance and quantitative kinetics before activation", ("reactome_insulin_receptor", "glucagon_creb_hepatic_control", "reactome_hgf_met", "reactome_il6_signaling", "wnt_beta_catenin_liver_regeneration", "reactome_adherens_junctions", "hepatocyte_connexin32_signal_propagation", "kemas2021_phh_glucose"), "A defined 1.7 uM insulin challenge has matched pAKT and PCK1/G6PC responses in PHH spheroids, but INSR surface abundance, receptor occupancy and complete kinetics remain unavailable."),
    ModelSurfaceAudit("cell_contact_geometry", "derived", "geometry_authoritative_runtime_spatial_state", False, "use engine-owned convex surfaces for signed gap, broad contact-patch geometry, membrane-domain labels, enter/stay/exit inputs and volume-preserving contact deformation; enforce the explicit 1% cross-system area-strain cap; do not use elapsed contact time as a causal parameter; keep force, adhesion, junction gating and biochemical activation blocked", ("olander2021_human_hepatocyte_size", "fabyan2026_human_liver_3d", "evans1976_human_membrane_area_lysis", "rawicz2000_bilayer_elasticity", "guillou2016_membrane_surface_reservoirs"), "The 18.4 um diameter is measured for isolated PHH batches and sets only an equivalent-volume scale. The regular truncated-octahedron boundary and affine deformation are kinematic proxies, not donor tissue morphometry or PHH rheology. One percent is an engineering cap equal to half the lower 2% human-RBC lysis bound. Constant-volume T-lymphocyte deformation supports only the kinematic principle and supplies no PHH parameter. Computed patch area and deformation cannot identify adhesion bond density, force, stiffness, receptor occupancy or gap-junction permeability."),
    ModelSurfaceAudit("brian2_intercellular_execution", "blocked", "optional_backend_gate", False, "require the pinned backend plus source-backed equations, complete units, calibrated parameters and geometry coupling", ("brian2_2_10_1", "brian2_custom_events"), "Brian2 is an equation/event executor, not a source of hepatocyte biology. No calibrated communication model is attached."),
    ModelSurfaceAudit("generative_hepatocyte_model", "blocked", "data_and_model_governance_boundary", False, "require donor-disjoint measured data, frozen schema, weight checksum, held-out evaluation and posterior predictive checks", ("autoencoding_variational_bayes", "scvi_single_cell_generative_model", "scgen_perturbation_model", "scvi_tools_documentation"), "No audited donor-resolved training bundle or validated model artifact is loaded; synthetic candidates cannot drive the mechanistic engine."),
    ModelSurfaceAudit("normalized_pool_engine", "schematic", "legacy_relative_state", False, "never use for quantitative validation", ("project_roadmap_07",), "All 48 pools are relative 0-1 placeholders."),
    ModelSurfaceAudit("organelle_functional_cycles", "schematic", "legacy_relative_state", False, "retain only as qualitative renderer driver", ("project_roadmap_07",), "Cycle rates, error fractions, damage and repair coefficients are uncalibrated."),
    ModelSurfaceAudit("organelle_failure_hazards", "disabled", "not_executed_without_calibration", False, "require a source-tagged calibration object", (), "Former per-hour base risks and stress weights were project assumptions."),
    ModelSurfaceAudit("cytokinesis_failure_probability", "disabled", "not_executed_without_calibration", False, "require measured context-specific probability", ("human_hepatocyte_binucleation",), "Binucleated-cell prevalence cannot be used as a per-division failure probability."),
    ModelSurfaceAudit("absolute_transporter_flux", "blocked", "qualitative_activity_only", False, "require active surface copies and matched turnover", ("human_mrp2_abundance_2012", "human_bsep_taurocholate_2013", "human_ntcp_uptake_2003"), "Total or membrane-fraction abundance is not active canalicular surface abundance."),
    ModelSurfaceAudit("glutathione_redox_kinetics", "blocked", "exploratory_network_only", False, "require compartment-resolved human GSH/GSSG/NADPH trajectories", ("human_liver_glutathione_1980", "primary_hepatocyte_isolation_metabolism_2018"), "Legacy GPx, reductase, PPP and ROS influx rates are placeholders; isolation changes these pools."),
    ModelSurfaceAudit("integrated_fuel_pathway_rates", "blocked", "exploratory_network_only", False, "replace pseudo-first-order magnitudes with fitted human fluxes", ("hepatic_glucose_homeostasis",), "Topology and stoichiometry are useful, but several absolute rates are illustrative."),
    ModelSurfaceAudit("endocrine_receptor_rate_coupling", "blocked", "measurement_gate_only", False, "require matched physiological exposure, receptor abundance/occupancy and dose-time response sufficient for a rate law", ("human_mixed_meal_endocrine_1996", "human_glycogen_hormone_clamp_1996", "kemas2021_phh_glucose"), "The PHH spheroid pAKT and gene-expression responses close part of the chain, but the 1.7 uM challenge is a conventional culture concentration and no INSR abundance, EC50, Hill coefficient or portal-matched kinetics is available."),
    ModelSurfaceAudit("cell_fate_thresholds", "blocked", "evidence_labels_only", False, "do not claim calibrated time-to-death", ("atp_death_switch", "human_bile_acid_death_mode"), "Relative stress thresholds are not matched human-hepatocyte commitment kinetics."),
    ModelSurfaceAudit("genome_expression", "derived", "structural_data_gated", False, "run dynamics only for calibrated genes", ("human_hepatocyte_proteome_2016",), "Reference coordinates are real; most donor expression and gene-specific kinetics are unknown."),
)


def scientific_model_audit_snapshot() -> dict[str, object]:
    blocked = tuple(item.id for item in MODEL_SURFACE_AUDIT if item.status in ("blocked", "disabled"))
    authoritative = tuple(item.id for item in MODEL_SURFACE_AUDIT if item.drives_scientific_validation)
    return {
        "status": "mixed_authority_research_preview",
        "authoritative_surfaces": authoritative,
        "blocked_or_disabled_surfaces": blocked,
        "surfaces": MODEL_SURFACE_AUDIT,
        "policy": "Only source-backed surfaces may drive scientific validation. Schematic and blocked surfaces may drive visualization but not quantitative claims.",
    }
