"""Quantitative (real-units) foundation for the hepatocyte model.

This package adds the absolute-scale layer the engine needs before it can run
stochastic biochemistry (SSA / chemical Langevin). The legacy deterministic
metabolism uses normalized [0, 1] pools; that layer is fine for coarse
visualization but cannot support reaction propensities, which are defined on
*molecule counts*.

Two pieces live here:

- ``geometry``: absolute hepatocyte cell + compartment volumes, plus the
  concentration <-> molecule-count conversions (Avogadro-based).
- ``species``: a source-grounded registry of physiological metabolite
  concentrations, each carrying provenance and an explicit confidence level.

Nothing here mutates the existing ``CellState``/``step_cell`` loop. It is a
self-contained foundation that later milestones build the stochastic core on.
"""

from cell_engine.quantitative.geometry import (
    AVOGADRO,
    HEPATOCYTE_CELL_VOLUME_L,
    HepatocyteGeometry,
    build_hepatocyte_geometry,
    concentration_mM_from_molecules,
    daughter_membrane_area_requirement,
    equivalent_sphere_radius_um,
    equivalent_sphere_surface_area_um2,
    molecules_from_concentration_mM,
    relative_membrane_area_from_biomass,
    relative_radius_from_biomass,
)
from cell_engine.quantitative.species import (
    HEPATOCYTE_SPECIES,
    QUANTITATIVE_SOURCES,
    SpeciesQuantity,
    species_copy_numbers,
)
from cell_engine.quantitative.phh_profiles import (
    DEFAULT_PHH_PROFILE_ID,
    PHH_NUTRITIONAL_PROFILES,
    PhhNutritionalProfile,
    PhhPoolValue,
    phh_profile,
    phh_profiles_snapshot,
)
from cell_engine.quantitative.phh_state import (
    QuantitativePhhState,
    QuantitativePoolState,
    build_quantitative_phh_state,
    quantitative_phh_state_snapshot,
    schematic_visual_state_snapshot,
    validate_quantitative_phh_state,
)
from cell_engine.quantitative.zonation import (
    HepaticZone,
    HumanHepatocyteZonationState,
    HumanMpsOxygenContext,
    ZONATION_SOURCES,
    build_human_hepatocyte_zonation,
    human_hepatocyte_zonation_snapshot,
    validate_human_hepatocyte_zonation,
)
from cell_engine.quantitative.homeostasis_v3 import (
    HOMEOSTASIS_V3_SOURCES,
    HumanNutritionalHomeostasisV3,
    build_human_nutritional_homeostasis_v3,
    human_nutritional_homeostasis_v3_snapshot,
    validate_human_nutritional_homeostasis_v3,
)
from cell_engine.quantitative.endocrine import (
    ENDOCRINE_SOURCES,
    CausalGlycogenBenchmark,
    HumanEndocrineContext,
    HumanMixedMealEndocrineTrajectory,
    build_causal_glycogen_benchmark,
    build_human_endocrine_context,
    build_human_mixed_meal_endocrine_trajectory,
    endocrine_profile_status,
    human_endocrine_context_snapshot,
    validate_human_endocrine_context,
)
from cell_engine.quantitative.human_validation_protocol import (
    HumanMixedMealValidationProtocol,
    ObservationResidual,
    ProtocolObservation,
    ScaleMatchedPrediction,
    build_human_mixed_meal_validation_protocol,
    compare_scale_matched_prediction,
    human_mixed_meal_validation_protocol_snapshot,
    validate_human_mixed_meal_validation_protocol,
)
from cell_engine.quantitative.phh_glucose_validation import (
    PHH_GLUCOSE_VALIDATION_SOURCES,
    HealthyPhhGlucoseValidation,
    load_healthy_phh_glucose_validation,
    healthy_phh_glucose_validation_snapshot,
    validate_healthy_phh_glucose_validation,
)
from cell_engine.quantitative.phh_spheroid_protocol import (
    PhhSpheroidModelPrediction,
    PhhSpheroidProtocolComparison,
    PhhSpheroidValidationProtocol,
    build_phh_spheroid_validation_protocol,
    compare_phh_spheroid_prediction,
    match_phh_spheroid_prediction,
    phh_spheroid_validation_protocol_snapshot,
    validate_phh_spheroid_validation_protocol,
)
from cell_engine.quantitative.phh_glucose_observability import (
    PHH_GLUCOSE_OBSERVABILITY_SOURCES,
    PhhCumulativeModelPoint,
    PhhCumulativeModelTrajectorySet,
    PhhGlucoseMeasurementProjection,
    PhhGlucoseObservabilityState,
    audit_phh_cumulative_model_input,
    build_phh_glucose_observability,
    phh_glucose_observability_snapshot,
    project_cumulative_trajectory_to_phh_windows,
    validate_phh_glucose_observability,
)
from cell_engine.quantitative.phh_albumin_secretion import (
    PHH_ALBUMIN_SECRETION_SOURCES,
    AlbuminCumulativeModelPoint,
    AlbuminCumulativeModelTrajectory,
    AlbuminMeasurementProjection,
    PhhAlbuminSecretionState,
    audit_albumin_cumulative_model_input,
    build_phh_albumin_secretion,
    mature_albumin_molecules_per_cell,
    mature_albumin_ng_per_1e6_cells,
    phh_albumin_secretion_snapshot,
    project_cumulative_albumin_to_assay,
    validate_phh_albumin_secretion,
)
from cell_engine.quantitative.phh_cyp_function import (
    PHH_CYP_FUNCTION_SOURCES,
    CypModelBatchPrediction,
    CypModelPredictionSet,
    CypSameFormatComparison,
    PhhCypFunctionState,
    audit_cyp_model_prediction,
    build_phh_cyp_function,
    compare_cyp_model_to_observations,
    phh_cyp_function_snapshot,
    validate_phh_cyp_function,
)
from cell_engine.quantitative.phh_biliary_excretion import (
    PHH_BILIARY_EXCRETION_SOURCES,
    BeiMeasurementProjection,
    BeiPairedConditionInput,
    PhhBiliaryExcretionState,
    audit_bei_paired_input,
    build_phh_biliary_excretion,
    calculate_bei_percent,
    phh_biliary_excretion_snapshot,
    project_paired_d8_tca_to_bei,
    validate_phh_biliary_excretion,
)
from cell_engine.quantitative.phh_identity_heterogeneity import (
    PHH_IDENTITY_HETEROGENEITY_SOURCES,
    PhhIdentityHeterogeneityState,
    build_phh_identity_heterogeneity,
    phh_identity_heterogeneity_snapshot,
    validate_phh_identity_heterogeneity,
)
from cell_engine.quantitative.phh_proteome_budget import (
    PHH_PROTEOME_BUDGET_SOURCES,
    PhhProteomeBudgetState,
    build_phh_proteome_budget,
    derive_compartment_protein_mass_budget,
    phh_proteome_budget_snapshot,
    validate_phh_proteome_budget,
)
from cell_engine.quantitative.phh_transporter_inventory import (
    PHH_TRANSPORTER_INVENTORY_SOURCES,
    PhhTransporterInventoryState,
    build_phh_transporter_inventory,
    copies_from_pmol_per_mg_and_pg_per_cell,
    phh_transporter_inventory_snapshot,
    validate_phh_transporter_inventory,
)
from cell_engine.quantitative.human_sch_bile_acids import (
    HUMAN_SCH_BILE_ACID_SOURCES,
    HumanSchBileAcidState,
    build_human_sch_bile_acids,
    calculate_matched_raw_bei_percent,
    human_sch_bile_acids_snapshot,
    validate_human_sch_bile_acids,
)

__all__ = [
    "AVOGADRO",
    "HEPATOCYTE_CELL_VOLUME_L",
    "HepatocyteGeometry",
    "build_hepatocyte_geometry",
    "concentration_mM_from_molecules",
    "daughter_membrane_area_requirement",
    "equivalent_sphere_radius_um",
    "equivalent_sphere_surface_area_um2",
    "molecules_from_concentration_mM",
    "relative_membrane_area_from_biomass",
    "relative_radius_from_biomass",
    "HEPATOCYTE_SPECIES",
    "QUANTITATIVE_SOURCES",
    "SpeciesQuantity",
    "species_copy_numbers",
    "DEFAULT_PHH_PROFILE_ID",
    "PHH_NUTRITIONAL_PROFILES",
    "PhhNutritionalProfile",
    "PhhPoolValue",
    "phh_profile",
    "phh_profiles_snapshot",
    "QuantitativePhhState",
    "QuantitativePoolState",
    "build_quantitative_phh_state",
    "quantitative_phh_state_snapshot",
    "schematic_visual_state_snapshot",
    "validate_quantitative_phh_state",
    "HepaticZone",
    "HumanHepatocyteZonationState",
    "HumanMpsOxygenContext",
    "ZONATION_SOURCES",
    "build_human_hepatocyte_zonation",
    "human_hepatocyte_zonation_snapshot",
    "validate_human_hepatocyte_zonation",
    "HOMEOSTASIS_V3_SOURCES",
    "HumanNutritionalHomeostasisV3",
    "build_human_nutritional_homeostasis_v3",
    "human_nutritional_homeostasis_v3_snapshot",
    "validate_human_nutritional_homeostasis_v3",
    "ENDOCRINE_SOURCES",
    "CausalGlycogenBenchmark",
    "HumanEndocrineContext",
    "HumanMixedMealEndocrineTrajectory",
    "build_causal_glycogen_benchmark",
    "build_human_endocrine_context",
    "build_human_mixed_meal_endocrine_trajectory",
    "endocrine_profile_status",
    "human_endocrine_context_snapshot",
    "validate_human_endocrine_context",
    "HumanMixedMealValidationProtocol",
    "ObservationResidual",
    "ProtocolObservation",
    "ScaleMatchedPrediction",
    "build_human_mixed_meal_validation_protocol",
    "compare_scale_matched_prediction",
    "human_mixed_meal_validation_protocol_snapshot",
    "validate_human_mixed_meal_validation_protocol",
    "PHH_GLUCOSE_VALIDATION_SOURCES",
    "HealthyPhhGlucoseValidation",
    "load_healthy_phh_glucose_validation",
    "healthy_phh_glucose_validation_snapshot",
    "validate_healthy_phh_glucose_validation",
    "PhhSpheroidModelPrediction",
    "PhhSpheroidProtocolComparison",
    "PhhSpheroidValidationProtocol",
    "build_phh_spheroid_validation_protocol",
    "compare_phh_spheroid_prediction",
    "match_phh_spheroid_prediction",
    "phh_spheroid_validation_protocol_snapshot",
    "validate_phh_spheroid_validation_protocol",
    "PHH_GLUCOSE_OBSERVABILITY_SOURCES",
    "PhhCumulativeModelPoint",
    "PhhCumulativeModelTrajectorySet",
    "PhhGlucoseMeasurementProjection",
    "PhhGlucoseObservabilityState",
    "audit_phh_cumulative_model_input",
    "build_phh_glucose_observability",
    "phh_glucose_observability_snapshot",
    "project_cumulative_trajectory_to_phh_windows",
    "validate_phh_glucose_observability",
    "PHH_ALBUMIN_SECRETION_SOURCES",
    "AlbuminCumulativeModelPoint",
    "AlbuminCumulativeModelTrajectory",
    "AlbuminMeasurementProjection",
    "PhhAlbuminSecretionState",
    "audit_albumin_cumulative_model_input",
    "build_phh_albumin_secretion",
    "mature_albumin_molecules_per_cell",
    "mature_albumin_ng_per_1e6_cells",
    "phh_albumin_secretion_snapshot",
    "project_cumulative_albumin_to_assay",
    "validate_phh_albumin_secretion",
    "PHH_CYP_FUNCTION_SOURCES",
    "CypModelBatchPrediction",
    "CypModelPredictionSet",
    "CypSameFormatComparison",
    "PhhCypFunctionState",
    "audit_cyp_model_prediction",
    "build_phh_cyp_function",
    "compare_cyp_model_to_observations",
    "phh_cyp_function_snapshot",
    "validate_phh_cyp_function",
    "PHH_BILIARY_EXCRETION_SOURCES",
    "BeiMeasurementProjection",
    "BeiPairedConditionInput",
    "PhhBiliaryExcretionState",
    "audit_bei_paired_input",
    "build_phh_biliary_excretion",
    "calculate_bei_percent",
    "phh_biliary_excretion_snapshot",
    "project_paired_d8_tca_to_bei",
    "validate_phh_biliary_excretion",
    "PHH_IDENTITY_HETEROGENEITY_SOURCES",
    "PhhIdentityHeterogeneityState",
    "build_phh_identity_heterogeneity",
    "phh_identity_heterogeneity_snapshot",
    "validate_phh_identity_heterogeneity",
    "PHH_PROTEOME_BUDGET_SOURCES",
    "PhhProteomeBudgetState",
    "build_phh_proteome_budget",
    "derive_compartment_protein_mass_budget",
    "phh_proteome_budget_snapshot",
    "validate_phh_proteome_budget",
    "PHH_TRANSPORTER_INVENTORY_SOURCES",
    "PhhTransporterInventoryState",
    "build_phh_transporter_inventory",
    "copies_from_pmol_per_mg_and_pg_per_cell",
    "phh_transporter_inventory_snapshot",
    "validate_phh_transporter_inventory",
    "HUMAN_SCH_BILE_ACID_SOURCES",
    "HumanSchBileAcidState",
    "build_human_sch_bile_acids",
    "calculate_matched_raw_bei_percent",
    "human_sch_bile_acids_snapshot",
    "validate_human_sch_bile_acids",
]
